:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__basesearchfactory]]
= BaseSearchFactory

Base factory to build elastic search requests.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory[`BaseSearchFactory`]
====


===== Namespace

`IO\Services\ItemSearch\Factories`





.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$aggregations`
||link:http://php.net/array[`array`^]
a|`$mutators`
||link:http://php.net/array[`array`^]
a|`$filters`
||link:http://php.net/array[`array`^]
a|`$resultFields`
||link:http://php.net/array[`array`^]
a|`$filterInstances`
||link:http://php.net/array[`array`^]
a|`$extensions`
||link:http://php.net/string[`string`^]
a|`$collapseField`
||xref:stable7@interface::Cloud.adoc#cloud_sorting_multiplesorting[`MultipleSorting`]
a|`$sorting`
||xref:stable7@interface::Cloud.adoc#cloud_scoremodifier_randomscore[`RandomScore`]
a|`$randomScoreModifier`
||link:http://php.net/int[`int`^]
a|`$page`
||link:http://php.net/int[`int`^]
a|`$itemsPerPage`
||link:http://php.net/string[`string`^]
a|`$pluginNamespace`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#inherit]
----

public inherit($searchBuilder, $inheritedProperties = []):xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[BaseSearchFactory]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_inherit[`BaseSearchFactory::inherit()`]
====




Create a new factory instance based on properties of an existing factory.

.*Parameters*
|===
|Type |Name |Description
|xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[`BaseSearchFactory`]
a|`$searchBuilder`
|The search factory to inherit properties from.

|link:http://php.net/array[`array`^]
a|`$inheritedProperties`
|List of properties to inherit or null to inherit all properties.
|===


[source%nowrap, php, subs=+macros]
[#withmutator]
----

public withMutator($mutator):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_withmutator[`BaseSearchFactory::withMutator()`]
====




Add a mutator

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Cloud.adoc#cloud_mutator_mutatorinterface[`MutatorInterface`]
a|`$mutator`
|
|===


[source%nowrap, php, subs=+macros]
[#createfilter]
----

public createFilter($filterClass):xref:stable7@interface::Cloud.adoc#cloud_type_typeinterface[TypeInterface]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_createfilter[`BaseSearchFactory::createFilter()`]
====




Add a filter. Will create a new instance of the filter class if not already created.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$filterClass`
|
|===


[source%nowrap, php, subs=+macros]
[#withfilter]
----

public withFilter($filter):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_withfilter[`BaseSearchFactory::withFilter()`]
====




Add a filter. Will override existing filter instances.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Cloud.adoc#cloud_type_typeinterface[`TypeInterface`]
a|`$filter`
|
|===


[source%nowrap, php, subs=+macros]
[#withresultfields]
----

public withResultFields($fields):xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[BaseSearchFactory]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_withresultfields[`BaseSearchFactory::withResultFields()`]
====




Set fields to be contained in search result.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^] \| link:http://php.net/array[`array`^]
a|`$fields`
|Reference to a json file to load fields from or a list of field names.
|===


[source%nowrap, php, subs=+macros]
[#getresultfields]
----

public getResultFields():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_getresultfields[`BaseSearchFactory::getResultFields()`]
====






[source%nowrap, php, subs=+macros]
[#withextension]
----

public withExtension($extensionClass, $extensionParams = []):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_withextension[`BaseSearchFactory::withExtension()`]
====




Add an extension.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$extensionClass`
|Extension class to add.

|link:http://php.net/array[`array`^]
a|`$extensionParams`
|Additional parameters to pass to extensions constructor
|===


[source%nowrap, php, subs=+macros]
[#getextensions]
----

public getExtensions():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_getextensions[`BaseSearchFactory::getExtensions()`]
====




Get all registered extensions

[source%nowrap, php, subs=+macros]
[#withaggregation]
----

public withAggregation($aggregation):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_withaggregation[`BaseSearchFactory::withAggregation()`]
====




Add an aggregation

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Cloud.adoc#cloud_aggregation_aggregationinterface[`AggregationInterface`]
a|`$aggregation`
|
|===


[source%nowrap, php, subs=+macros]
[#setpage]
----

public setPage($page, $itemsPerPage):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_setpage[`BaseSearchFactory::setPage()`]
====




Set pagination parameters.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$page`
|

|link:http://php.net/int[`int`^]
a|`$itemsPerPage`
|
|===


[source%nowrap, php, subs=+macros]
[#sortby]
----

public sortBy($field, $order = \Plenty\Modules\Webshop\ItemSearch\Factories\VariationSearchFactory::SORTING_ORDER_DESC):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_sortby[`BaseSearchFactory::sortBy()`]
====




Add sorting parameters

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$field`
|The field to order by

|link:http://php.net/string[`string`^]
a|`$order`
|Direction to order results. Possible values: 'asc' or 'desc'
|===


[source%nowrap, php, subs=+macros]
[#sortbymultiple]
----

public sortByMultiple($sortingList):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_sortbymultiple[`BaseSearchFactory::sortByMultiple()`]
====




Add multiple sorting parameters

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$sortingList`
|List of sorting parameters. Each entry should have a 'field' and an 'order' property.
|===


[source%nowrap, php, subs=+macros]
[#setorder]
----

public setOrder($idList):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_setorder[`BaseSearchFactory::setOrder()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$idList`
|
|===


[source%nowrap, php, subs=+macros]
[#groupby]
----

public groupBy($field):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_groupby[`BaseSearchFactory::groupBy()`]
====




Group results by field

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$field`
|The field to group properties by.
|===


[source%nowrap, php, subs=+macros]
[#build]
----

public build():xref:stable7@interface::Cloud.adoc#cloud_document_documentsearch[DocumentSearch]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_build[`BaseSearchFactory::build()`]
====




Build the elastic search request.

[source%nowrap, php, subs=+macros]
[#preparesearch]
----

public prepareSearch($source):xref:stable7@interface::Cloud.adoc#cloud_document_documentsearch[DocumentSearch]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_basesearchfactory_preparesearch[`BaseSearchFactory::prepareSearch()`]
====




Build the search instance itself. May be overridden by concrete factories.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Cloud.adoc#cloud_source_includesource[`IncludeSource`]
a|`$source`
|
|===


