:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__facetsearchfactory]]
= FacetSearchFactory

Concrete factory to build facet searches.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_facetsearchfactory[`FacetSearchFactory`]
====


===== Namespace

`IO\Services\ItemSearch\Factories`

===== Extends
xref:IO/Services/ItemSearch/Factories/VariationSearchFactory.adoc#[`VariationSearchFactory`]




.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$facetValues`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#create]
----

public create($facets):xref:IO/Services/ItemSearch/Factories/FacetSearchFactory.adoc#[FacetSearchFactory]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_facetsearchfactory_create[`FacetSearchFactory::create()`]
====




Create a factory instance depending on a given set of facet values.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^] \| link:http://php.net/array[`array`^]
a|`$facets`
|List of active facet values. If string is given, it will be exploded by ',' to a list of values.
|===


[source%nowrap, php, subs=+macros]
[#preparesearch]
----

public prepareSearch($source):xref:stable7@interface::Cloud.adoc#cloud_document_documentsearch[DocumentSearch]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_facetsearchfactory_preparesearch[`FacetSearchFactory::prepareSearch()`]
====




Build facet search classes

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Cloud.adoc#cloud_source_includesource[`IncludeSource`]
a|`$source`
|
|===


[source%nowrap, php, subs=+macros]
[#withminimumcount]
----

public withMinimumCount():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_facetsearchfactory_withminimumcount[`FacetSearchFactory::withMinimumCount()`]
====




Register extension to filter facets by minimum hit count.

