:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__multisearchfactory]]
= MultiSearchFactory

Factory to build an elastic search multisearch request by collecting multiple search factory instances.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_multisearchfactory[`MultiSearchFactory`]
====


===== Namespace

`IO\Services\ItemSearch\Factories`





.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$searches`
||link:http://php.net/array[`array`^]
a|`$extensions`
||link:http://php.net/string[`string`^]
a|`$pluginNamespace`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#getsearches]
----

public getSearches():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_multisearchfactory_getsearches[`MultiSearchFactory::getSearches()`]
====




Get all registered searches

[source%nowrap, php, subs=+macros]
[#getextensions]
----

public getExtensions():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_multisearchfactory_getextensions[`MultiSearchFactory::getExtensions()`]
====




Get all registered extensions

[source%nowrap, php, subs=+macros]
[#addsearch]
----

public addSearch($resultName, $searchBuilder):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_multisearchfactory_addsearch[`MultiSearchFactory::addSearch()`]
====




Add a search factory instance to be included in current mutlisearch request.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$resultName`
|An unique name for the search. Results of this search will be accessible by this key.

|xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[`BaseSearchFactory`]
a|`$searchBuilder`
|A search factory
|===


[source%nowrap, php, subs=+macros]
[#getresults]
----

public getResults():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_multisearchfactory_getresults[`MultiSearchFactory::getResults()`]
====




Execute the multisearch and collect results.

