:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__variationsearchfactory]]
= VariationSearchFactory

Concrete factory to build variation searches

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory[`VariationSearchFactory`]
====


===== Namespace

`IO\Services\ItemSearch\Factories`

===== Extends
xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[`BaseSearchFactory`]




.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$isAdminPreview`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct()

----







[source%nowrap, php, subs=+macros]
[#setadminpreview]
----

public setAdminPreview($isAdminPreview):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_setadminpreview[`VariationSearchFactory::setAdminPreview()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$isAdminPreview`
|
|===


[source%nowrap, php, subs=+macros]
[#isactive]
----

public isActive():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_isactive[`VariationSearchFactory::isActive()`]
====




Filter active variations

[source%nowrap, php, subs=+macros]
[#isinactive]
----

public isInactive():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_isinactive[`VariationSearchFactory::isInactive()`]
====




Filter inactive variations

[source%nowrap, php, subs=+macros]
[#hasitemid]
----

public hasItemId($itemId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasitemid[`VariationSearchFactory::hasItemId()`]
====




Filter variation by a single item id

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|Item id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasitemids]
----

public hasItemIds($itemIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasitemids[`VariationSearchFactory::hasItemIds()`]
====




Filter variations by multiple item ids

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemIds`
|List of item ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasvariationid]
----

public hasVariationId($variationId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasvariationid[`VariationSearchFactory::hasVariationId()`]
====




Filter variation by a single variation id.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|The variation id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasvariationids]
----

public hasVariationIds($variationIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasvariationids[`VariationSearchFactory::hasVariationIds()`]
====




Filter variations by multiple variation ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationIds`
|List of variation ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasatleastoneavailability]
----

public hasAtLeastOneAvailability($availabilityIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasatleastoneavailability[`VariationSearchFactory::hasAtLeastOneAvailability()`]
====




Filter variations by multiple availability ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$availabilityIds`
|List of availability ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hassupplier]
----

public hasSupplier($supplierId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hassupplier[`VariationSearchFactory::hasSupplier()`]
====




Filter variations by multiple availability ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$supplierId`
|The supplier id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasmanufacturer]
----

public hasManufacturer($manufacturerId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasmanufacturer[`VariationSearchFactory::hasManufacturer()`]
====




Filter manufacturers by id.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$manufacturerId`
|To filter by manufacturer
|===


[source%nowrap, php, subs=+macros]
[#haseachproperty]
----

public hasEachProperty($propertyIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_haseachproperty[`VariationSearchFactory::hasEachProperty()`]
====




Filter variations by multiple property ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$propertyIds`
|The property ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#ismain]
----

public isMain():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_ismain[`VariationSearchFactory::isMain()`]
====




Filter only main variations

[source%nowrap, php, subs=+macros]
[#ischild]
----

public isChild():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_ischild[`VariationSearchFactory::isChild()`]
====




Filter only child variations

[source%nowrap, php, subs=+macros]
[#ishiddenincategorylist]
----

public isHiddenInCategoryList($isHidden = true):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_ishiddenincategorylist[`VariationSearchFactory::isHiddenInCategoryList()`]
====




Filter by visibility in category list.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$isHidden`
|Visibility in category list to filter by.
|===


[source%nowrap, php, subs=+macros]
[#issalable]
----

public isSalable():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_issalable[`VariationSearchFactory::isSalable()`]
====




Filter variations by isSalable flag

[source%nowrap, php, subs=+macros]
[#isvisibleforclient]
----

public isVisibleForClient($clientId = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_isvisibleforclient[`VariationSearchFactory::isVisibleForClient()`]
====




Filter variations by visibility for client

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$clientId`
|The client id to filter by. If null, default client id on application will be used.
|===


[source%nowrap, php, subs=+macros]
[#hasnameinlanguage]
----

public hasNameInLanguage($type = \Plenty\Modules\Item\Search\Filter\TextFilter::FILTER_ANY_NAME, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasnameinlanguage[`VariationSearchFactory::hasNameInLanguage()`]
====




Filter variations having texts in a given language.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$type`
|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

|link:http://php.net/string[`string`^]
a|`$lang`
|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php, subs=+macros]
[#isincategory]
----

public isInCategory($categoryId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_isincategory[`VariationSearchFactory::isInCategory()`]
====




Filter variations contained in a category.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$categoryId`
|A category id to filter variations by.
|===


[source%nowrap, php, subs=+macros]
[#hasatleastoneprice]
----

public hasAtLeastOnePrice($priceIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasatleastoneprice[`VariationSearchFactory::hasAtLeastOnePrice()`]
====




Filter variations having at least on price.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$priceIds`
|List of price ids to filter variations by
|===


[source%nowrap, php, subs=+macros]
[#haspriceforcustomer]
----

public hasPriceForCustomer():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_haspriceforcustomer[`VariationSearchFactory::hasPriceForCustomer()`]
====




Filter variations having at least one price accessible by current customer.

[source%nowrap, php, subs=+macros]
[#haspriceinrange]
----

public hasPriceInRange($priceMin, $priceMax):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_haspriceinrange[`VariationSearchFactory::hasPriceInRange()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[`float`^]
a|`$priceMin`
|

|link:http://php.net/float[`float`^]
a|`$priceMax`
|
|===


[source%nowrap, php, subs=+macros]
[#hastag]
----

public hasTag($tagId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hastag[`VariationSearchFactory::hasTag()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$tagId`
|
|===


[source%nowrap, php, subs=+macros]
[#hasanytag]
----

public hasAnyTag($tagIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasanytag[`VariationSearchFactory::hasAnyTag()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$tagIds`
|
|===


[source%nowrap, php, subs=+macros]
[#groupbytemplateconfig]
----

public groupByTemplateConfig($key = &quot;ids.itemAttributeValue&quot;):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_groupbytemplateconfig[`VariationSearchFactory::groupByTemplateConfig()`]
====




Group results depending on a config value.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#iscrosssellingitem]
----

public isCrossSellingItem($itemId, $relation):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_iscrosssellingitem[`VariationSearchFactory::isCrossSellingItem()`]
====




Filter variations having a cross selling relation to a given item.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|Item id to filter cross selling items for

|link:http://php.net/string[`string`^]
a|`$relation`
|The relation of cross selling items.
|===


[source%nowrap, php, subs=+macros]
[#hasfacets]
----

public hasFacets($facetValues, $clientId = null, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasfacets[`VariationSearchFactory::hasFacets()`]
====




Filter variations by facets.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^] \| link:http://php.net/array[`array`^]
a|`$facetValues`
|List of facet values. If string is given, it will be exploded by ';'

|link:http://php.net/int[`int`^]
a|`$clientId`
|Client id to filter facets by. If null, default client id from application will be used.

|link:http://php.net/string[`string`^]
a|`$lang`
|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#hassearchstring]
----

public hasSearchString($query, $lang = null, $searchType = \Plenty\Modules\Cloud\ElasticSearch\Lib\ElasticSearch::SEARCH_TYPE_EXACT, $operator = \Plenty\Modules\Cloud\ElasticSearch\Lib\ElasticSearch::OR_OPERATOR):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hassearchstring[`VariationSearchFactory::hasSearchString()`]
====




Filter variations by given search string.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$query`
|The search string to filter variations by

|link:http://php.net/string[`string`^]
a|`$lang`
|The language to apply search on. If null, default language from session will be used

|link:http://php.net/string[`string`^]
a|`$searchType`
|Type of the search ('exact', 'fuzzy', 'autocomplete')

|link:http://php.net/string[`string`^]
a|`$operator`
|Operator ot be used for search
|===


[source%nowrap, php, subs=+macros]
[#hasnamestring]
----

public hasNameString($query, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_hasnamestring[`VariationSearchFactory::hasNameString()`]
====




Filter variations by searching names

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$query`
|The search string

|link:http://php.net/string[`string`^]
a|`$lang`
|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#withlanguage]
----

public withLanguage($lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withlanguage[`VariationSearchFactory::withLanguage()`]
====




Only request given language.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$lang`
|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#withimages]
----

public withImages($clientId = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withimages[`VariationSearchFactory::withImages()`]
====




Include images in result

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$clientId`
|The client id to get images for. If null, default client id from application will be used.
|===


[source%nowrap, php, subs=+macros]
[#withattributes]
----

public withAttributes():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withattributes[`VariationSearchFactory::withAttributes()`]
====




Includes VariatonAttributeMap for variation select

[source%nowrap, php, subs=+macros]
[#withpropertygroups]
----

public withPropertyGroups():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withpropertygroups[`VariationSearchFactory::withPropertyGroups()`]
====






[source%nowrap, php, subs=+macros]
[#withorderpropertyselectionvalues]
----

public withOrderPropertySelectionValues():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withorderpropertyselectionvalues[`VariationSearchFactory::withOrderPropertySelectionValues()`]
====






[source%nowrap, php, subs=+macros]
[#withvariationproperties]
----

public withVariationProperties():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withvariationproperties[`VariationSearchFactory::withVariationProperties()`]
====






[source%nowrap, php, subs=+macros]
[#withurls]
----

public withUrls():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withurls[`VariationSearchFactory::withUrls()`]
====




Append URLs to result.

[source%nowrap, php, subs=+macros]
[#withprices]
----

public withPrices($params):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withprices[`VariationSearchFactory::withPrices()`]
====




Append prices to result.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$params`
|Params to be passed to price search.
|===


[source%nowrap, php, subs=+macros]
[#withcurrentcategory]
----

public withCurrentCategory():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withcurrentcategory[`VariationSearchFactory::withCurrentCategory()`]
====




Set result as current category

[source%nowrap, php, subs=+macros]
[#withdefaultimage]
----

public withDefaultImage():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withdefaultimage[`VariationSearchFactory::withDefaultImage()`]
====




Append default item image if images are requested by result fields and item does not have any image

[source%nowrap, php, subs=+macros]
[#withbundlecomponents]
----

public withBundleComponents():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withbundlecomponents[`VariationSearchFactory::withBundleComponents()`]
====






[source%nowrap, php, subs=+macros]
[#withlinktocontent]
----

public withLinkToContent():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withlinktocontent[`VariationSearchFactory::withLinkToContent()`]
====






[source%nowrap, php, subs=+macros]
[#withgroupedattributevalues]
----

public withGroupedAttributeValues():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withgroupedattributevalues[`VariationSearchFactory::withGroupedAttributeValues()`]
====






[source%nowrap, php, subs=+macros]
[#withreducedresults]
----

public withReducedResults($removeProperties = false):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withreducedresults[`VariationSearchFactory::withReducedResults()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$removeProperties`
|
|===


[source%nowrap, php, subs=+macros]
[#withavailability]
----

public withAvailability():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withavailability[`VariationSearchFactory::withAvailability()`]
====






[source%nowrap, php, subs=+macros]
[#withtags]
----

public withTags():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_factories_variationsearchfactory_withtags[`VariationSearchFactory::withTags()`]
====






