:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__variationsearchfactory]]
= VariationSearchFactory

Concrete factory to build variation searches



===== Namespace

`IO\Services\ItemSearch\Factories`

===== Extends
xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[`BaseSearchFactory`]



.Constants
|===
|Type |Name |Value |Description

|link:http://php.net/string[string^]
a|`SORTING_ORDER_ASC`
|'asc'
|
|link:http://php.net/string[string^]
a|`SORTING_ORDER_DESC`
|'desc'
|
|link:http://php.net/string[string^]
a|`INHERIT_AGGREGATIONS`
|'aggregations'
|
|link:http://php.net/string[string^]
a|`INHERIT_COLLAPSE`
|'collapse'
|
|link:http://php.net/string[string^]
a|`INHERIT_EXTENSIONS`
|'extensions'
|
|link:http://php.net/string[string^]
a|`INHERIT_FILTERS`
|'filters'
|
|link:http://php.net/string[string^]
a|`INHERIT_MUTATORS`
|'mutators'
|
|link:http://php.net/string[string^]
a|`INHERIT_PAGINATION`
|'pagination'
|
|link:http://php.net/string[string^]
a|`INHERIT_RESULT_FIELDS`
|'resultFields'
|
|link:http://php.net/string[string^]
a|`INHERIT_SORTING`
|'sorting'
|
|===


.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$isAdminPreview`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct()

----







[source%nowrap, php, subs=+macros]
[#isactive]
----

public isActive():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter active variations

[source%nowrap, php, subs=+macros]
[#isinactive]
----

public isInactive():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter inactive variations

[source%nowrap, php, subs=+macros]
[#hasitemid]
----

public hasItemId($itemId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variation by a single item id

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|Item id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasitemids]
----

public hasItemIds($itemIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by multiple item ids

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemIds`
|List of item ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasvariationid]
----

public hasVariationId($variationId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variation by a single variation id.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|The variation id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasvariationids]
----

public hasVariationIds($variationIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by multiple variation ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationIds`
|List of variation ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasatleastoneavailability]
----

public hasAtLeastOneAvailability($availabilityIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by multiple availability ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$availabilityIds`
|List of availability ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hassupplier]
----

public hasSupplier($supplierId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by multiple availability ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$supplierId`
|The supplier id to filter by.
|===


[source%nowrap, php, subs=+macros]
[#hasmanufacturer]
----

public hasManufacturer($manufacturerId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter manufacturers by id.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$manufacturerId`
|To filter by manufacturer
|===


[source%nowrap, php, subs=+macros]
[#haseachproperty]
----

public hasEachProperty($propertyIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by multiple property ids.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$propertyIds`
|The property ids to filter by.
|===


[source%nowrap, php, subs=+macros]
[#ismain]
----

public isMain():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter only main variations

[source%nowrap, php, subs=+macros]
[#ischild]
----

public isChild():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter only child variations

[source%nowrap, php, subs=+macros]
[#ishiddenincategorylist]
----

public isHiddenInCategoryList($isHidden = true):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter by visibility in category list.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$isHidden`
|Visibility in category list to filter by.
|===


[source%nowrap, php, subs=+macros]
[#issalable]
----

public isSalable():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by isSalable flag

[source%nowrap, php, subs=+macros]
[#isvisibleforclient]
----

public isVisibleForClient($clientId = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by visibility for client

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$clientId`
|The client id to filter by. If null, default client id on application will be used.
|===


[source%nowrap, php, subs=+macros]
[#hasnameinlanguage]
----

public hasNameInLanguage($type = \Plenty\Modules\Item\Search\Filter\TextFilter::FILTER_ANY_NAME, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations having texts in a given language.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$type`
|The text field to filter by ('hasAny', 'hasName1', 'hasName2', 'hasName3')

|link:http://php.net/string[`string`^]
a|`$lang`
|The language to filter by. If null, language defined in session will be used.
|===


[source%nowrap, php, subs=+macros]
[#isincategory]
----

public isInCategory($categoryId):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations contained in a category.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$categoryId`
|A category id to filter variations by.
|===


[source%nowrap, php, subs=+macros]
[#hasatleastoneprice]
----

public hasAtLeastOnePrice($priceIds):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations having at least on price.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$priceIds`
|List of price ids to filter variations by
|===


[source%nowrap, php, subs=+macros]
[#haspriceforcustomer]
----

public hasPriceForCustomer():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations having at least one price accessible by current customer.

[source%nowrap, php, subs=+macros]
[#haspriceinrange]
----

public hasPriceInRange()

----







[source%nowrap, php, subs=+macros]
[#hastag]
----

public hasTag($tagId)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$tagId`
|
|===


[source%nowrap, php, subs=+macros]
[#hasanytag]
----

public hasAnyTag($tagIds)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$tagIds`
|
|===


[source%nowrap, php, subs=+macros]
[#groupbytemplateconfig]
----

public groupByTemplateConfig($key = &quot;ids.itemAttributeValue&quot;):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Group results depending on a config value.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#iscrosssellingitem]
----

public isCrossSellingItem($itemId, $relation):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations having a cross selling relation to a given item.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|Item id to filter cross selling items for

|link:http://php.net/string[`string`^]
a|`$relation`
|The relation of cross selling items.
|===


[source%nowrap, php, subs=+macros]
[#hasfacets]
----

public hasFacets($facetValues, $clientId = null, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by facets.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^] \| link:http://php.net/array[`array`^]
a|`$facetValues`
|List of facet values. If string is given, it will be exploded by ';'

|link:http://php.net/int[`int`^]
a|`$clientId`
|Client id to filter facets by. If null, default client id from application will be used.

|link:http://php.net/string[`string`^]
a|`$lang`
|Language to filter facets by. If null, active language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#hassearchstring]
----

public hasSearchString($query, $lang = null, $searchType = \Plenty\Modules\Cloud\ElasticSearch\Lib\ElasticSearch::SEARCH_TYPE_EXACT, $operator = \Plenty\Modules\Cloud\ElasticSearch\Lib\ElasticSearch::OR_OPERATOR):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by given search string.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$query`
|The search string to filter variations by

|link:http://php.net/string[`string`^]
a|`$lang`
|The language to apply search on. If null, default language from session will be used

|link:http://php.net/string[`string`^]
a|`$searchType`
|Type of the search ('exact', 'fuzzy', 'autocomplete')

|link:http://php.net/string[`string`^]
a|`$operator`
|Operator ot be used for search
|===


[source%nowrap, php, subs=+macros]
[#hasnamestring]
----

public hasNameString($query, $lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Filter variations by searching names

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$query`
|The search string

|link:http://php.net/string[`string`^]
a|`$lang`
|Language to apply search on. If null, default language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#withlanguage]
----

public withLanguage($lang = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Only request given language.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$lang`
|Language to get texts for. If null, default language from session will be used.
|===


[source%nowrap, php, subs=+macros]
[#withimages]
----

public withImages($clientId = null):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Include images in result

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$clientId`
|The client id to get images for. If null, default client id from application will be used.
|===


[source%nowrap, php, subs=+macros]
[#withattributes]
----

public withAttributes():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Includes VariatonAttributeMap for variation select

[source%nowrap, php, subs=+macros]
[#withpropertygroups]
----

public withPropertyGroups()

----







[source%nowrap, php, subs=+macros]
[#withorderpropertyselectionvalues]
----

public withOrderPropertySelectionValues()

----







[source%nowrap, php, subs=+macros]
[#withvariationproperties]
----

public withVariationProperties()

----







[source%nowrap, php, subs=+macros]
[#withurls]
----

public withUrls():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Append URLs to result.

[source%nowrap, php, subs=+macros]
[#withprices]
----

public withPrices($params):xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Append prices to result.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$params`
|Params to be passed to price search.
|===


[source%nowrap, php, subs=+macros]
[#withcurrentcategory]
----

public withCurrentCategory():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Set result as current category

[source%nowrap, php, subs=+macros]
[#withdefaultimage]
----

public withDefaultImage():xref:IO/Services/ItemSearch/Factories.adoc#[Factories]

----





Append default item image if images are requested by result fields and item does not have any image

[source%nowrap, php, subs=+macros]
[#withbundlecomponents]
----

public withBundleComponents()

----







[source%nowrap, php, subs=+macros]
[#withlinktocontent]
----

public withLinkToContent()

----







[source%nowrap, php, subs=+macros]
[#withgroupedattributevalues]
----

public withGroupedAttributeValues()

----







[source%nowrap, php, subs=+macros]
[#withreducedresults]
----

public withReducedResults($removeProperties = false)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$removeProperties`
|
|===


[source%nowrap, php, subs=+macros]
[#withavailability]
----

public withAvailability()

----







[source%nowrap, php, subs=+macros]
[#withtags]
----

public withTags()

----







