:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__languagemap]]
= LanguageMap



[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_localizationrepositorycontract[`LocalizationRepositoryContract`]
====


===== Namespace

`IO\Helper`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$locales`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$languages`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#getlocale]
----

public static getLocale()

----

[WARNING]
.Deprecated! 
====

sin  ce 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_localizationrepositorycontract_getlocale[`LocalizationRepositoryContract::getLocale()`]
====






[source%nowrap, php, subs=+macros]
[#getlanguagecode]
----

public static getLanguageCode($countryCode = null)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_localizationrepositorycontract_getlanguagecode[`LocalizationRepositoryContract::getLanguageCode()`]
====






.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$countryCode`
|
|===


[source%nowrap, php, subs=+macros]
[#getcountrycode]
----

public static getCountryCode($language = null)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

====






.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$language`
|
|===


