:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__pluginconfig]]
= PluginConfig



[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig[`PluginConfig`]
====


===== Namespace

`IO\Helper`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$pluginName`
|| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_plugin_configrepository[`ConfigRepository`]
a|`$configRepository`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct()

----







[source%nowrap, php, subs=+macros]
[#getmultiselectvalue]
----

public getMultiSelectValue($key, $possibleValues = [], $default = null):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig_getmultiselectvalue[`PluginConfig::getMultiSelectValue()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|

|link:http://php.net/array[`array`^]
a|`$possibleValues`
|

|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$default`
|
|===


[source%nowrap, php, subs=+macros]
[#gettextvalue]
----

public getTextValue($key, $default = &quot;&quot;, $transformDefault = &quot;&quot;):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig_gettextvalue[`PluginConfig::getTextValue()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|

|link:http://php.net/string[`string`^]
a|`$default`
|

|link:http://php.net/string[`string`^]
a|`$transformDefault`
|
|===


[source%nowrap, php, subs=+macros]
[#getintegervalue]
----

public getIntegerValue($key, $default):link:http://php.net/int[int^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig_getintegervalue[`PluginConfig::getIntegerValue()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|

|link:http://php.net/int[`int`^]
a|`$default`
|
|===


[source%nowrap, php, subs=+macros]
[#getbooleanvalue]
----

public getBooleanValue($key, $default = false):link:http://php.net/bool[bool^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig_getbooleanvalue[`PluginConfig::getBooleanValue()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|

|link:http://php.net/bool[`bool`^]
a|`$default`
|
|===


[source%nowrap, php, subs=+macros]
[#getconfigvalue]
----

public getConfigValue($key, $default = null):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_pluginconfig_getconfigvalue[`PluginConfig::getConfigValue()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|

|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$default`
|
|===


