:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__variationpricelist]]
= VariationPriceList



[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist[`VariationPriceList`]
====


===== Namespace

`IO\Helper`




.Constants
|===
|Type |Name |Value |Description

|link:http://php.net/string[string^]
a|`TYPE_DEFAULT`
|'default'
|
|link:http://php.net/string[string^]
a|`TYPE_RRP`
|'rrp'
|
|link:http://php.net/string[string^]
a|`TYPE_SPECIAL_OFFER`
|'specialOffer'
|
|===


.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$basePrices`
||link:http://php.net/int[`int`^]
a|`$itemId`
||link:http://php.net/int[`int`^]
a|`$variationId`
||link:http://php.net/float[`float`^]
a|`$minimumOrderQuantity`
||link:http://php.net/float[`float`^]
a|`$maximumOrderQuantity`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$lot`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$unit`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$prices`
||xref:IO/Extensions/Filters/NumberFormatFilter.adoc#[`NumberFormatFilter`]
a|`$numberFormatFilter`
||xref:IO/Services/UnitService.adoc#[`UnitService`]
a|`$unitService`
||xref:stable7@interface::Liveshopping.adoc#liveshopping_contracts_liveshoppingrepositorycontract[`LiveShoppingRepositoryContract`]
a|`$liveShoppingRepo`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$showNetPrice`
||xref:stable7@interface::Item.adoc#item_models_salespricesearchresponse[`SalesPriceSearchResponse`]
a|`$defaultPrice`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$cache`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct()

----







[source%nowrap, php, subs=+macros]
[#create]
----

public static create($variationId, $itemId, $minimumOrderQuantity, $maximumOrderQuantity = null, $lot, $unit = null):xref:IO/Helper/VariationPriceList.adoc#[VariationPriceList]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_create[`VariationPriceList::create()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|

|link:http://php.net/int[`int`^]
a|`$itemId`
|

|link:http://php.net/int[`int`^]
a|`$minimumOrderQuantity`
|

|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$maximumOrderQuantity`
|

|link:http://php.net/int[`int`^]
a|`$lot`
|

|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$unit`
|
|===


[source%nowrap, php, subs=+macros]
[#findpriceforquantity]
----

public findPriceForQuantity($quantity, $type = self::TYPE_DEFAULT):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_findpriceforquantity[`VariationPriceList::findPriceForQuantity()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[`float`^]
a|`$quantity`
|

|link:http://php.net/string[`string`^]
a|`$type`
|
|===


[source%nowrap, php, subs=+macros]
[#getgraduatedprices]
----

public getGraduatedPrices($showNetPrice = false):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_getgraduatedprices[`VariationPriceList::getGraduatedPrices()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$showNetPrice`
|
|===


[source%nowrap, php, subs=+macros]
[#getbaseprice]
----

public getBasePrice($unitPrice, $currency, $lang = null):link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_getbaseprice[`VariationPriceList::getBasePrice()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[`float`^]
a|`$unitPrice`
|

|link:http://php.net/string[`string`^]
a|`$currency`
|

|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$lang`
|
|===


[source%nowrap, php, subs=+macros]
[#toarray]
----

public toArray($quantity = null):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_toarray[`VariationPriceList::toArray()`]
====






.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$quantity`
|
|===


[source%nowrap, php, subs=+macros]
[#getcalculatedprices]
----

public getCalculatedPrices($quantity = null):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_getcalculatedprices[`VariationPriceList::getCalculatedPrices()`]
====






.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-null::null.adoc#[`null`]
a|`$quantity`
|
|===


[source%nowrap, php, subs=+macros]
[#convertcurrency]
----

public convertCurrency($value):link:http://php.net/float[float^] \| link:http://php.net/int[int^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_convertcurrency[`VariationPriceList::convertCurrency()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/float[`float`^]
a|`$value`
|
|===


[source%nowrap, php, subs=+macros]
[#convertgrossnet]
----

public convertGrossNet()

----







[source%nowrap, php, subs=+macros]
[#getdefaultprice]
----

public getDefaultPrice():link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_variationpricelist_getdefaultprice[`VariationPriceList::getDefaultPrice()`]
====






[source%nowrap, php, subs=+macros]
[#frommemorycache]
----

public fromMemoryCache()

----







[source%nowrap, php, subs=+macros]
[#resetmemorycache]
----

public resetMemoryCache($key = null)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$key`
|
|===


