:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__singleitem]]
= SingleItem

Search preset for single items +
Available options: +
- itemId:        Item id to get +
- variationId:   Variation id to get. If not defined, plugin configuration will be considered if main or child variation should be displayed. +
- setCategory:   Flag indicating if item should be set as current item to be displayed in breadcrumbs

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_singleitem[`SingleItem`]
====


===== Namespace

`IO\Services\ItemSearch\SearchPresets`


===== Implements
xref:IO/Services/ItemSearch/SearchPresets/SearchPreset.adoc#[`SearchPreset`]




===== Methods

[source%nowrap, php, subs=+macros]
[#getsearchfactory]
----

public static getSearchFactory($options):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_searchpreset_getsearchfactory[`SearchPreset::getSearchFactory()`]
====




Get the search factory from the preset.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$options`
|
|===


