:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__tagitems]]
= TagItems

Search preset for tagged variations +
Available options (see VariationList for inherited options) +
- tagIds: List of tag ids to get assigned items for

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_tagitems[`TagItems`]
====


===== Namespace

`IO\Services\ItemSearch\SearchPresets`

===== Extends
xref:IO/Services/ItemSearch/SearchPresets/VariationList.adoc#[`VariationList`]

===== Implements
xref:IO/Services/ItemSearch/SearchPresets/SearchPreset.adoc#[`SearchPreset`]




===== Methods

[source%nowrap, php, subs=+macros]
[#getsearchfactory]
----

public static getSearchFactory($options):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_searchpreset_getsearchfactory[`SearchPreset::getSearchFactory()`]
====




Get the search factory from the preset.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$options`
|
|===


