:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__variationlist]]
= VariationList

Search preset for variation lists. +
Available options: +
- variationIds:      List of variations to receive. +
- sorting:           Configuration value to get sorting for. +
- sortingField:      Field to sort items by. Will be appended to sorting list if sorting configuration is defined. +
- sortingOrder:      Order to sort items with (&#039;asc&#039;, &#039;desc&#039;) +
- page:              The current page +
- itemsPerPage:      Number of items per page +
- excludeFromCache:  Set to true if results should not be linked to response

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_variationlist[`VariationList`]
====


===== Namespace

`IO\Services\ItemSearch\SearchPresets`


===== Implements
xref:IO/Services/ItemSearch/SearchPresets/SearchPreset.adoc#[`SearchPreset`]




===== Methods

[source%nowrap, php, subs=+macros]
[#getsearchfactory]
----

public static getSearchFactory($options):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_searchpresets_searchpreset_getsearchfactory[`SearchPreset::getSearchFactory()`]
====




Get the search factory from the preset.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$options`
|
|===


