:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__facetextensioncontainer]]
= FacetExtensionContainer



[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_facetextensioncontainer[`FacetExtensionContainer`]
====


===== Namespace

`IO\Services\ItemSearch\Helper`





.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$facetExtensionsList`
|| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_events_dispatcher[`Dispatcher`]
a|`$dispatcher`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($dispatcher)

----





FacetExtensionContainer constructor.

.*Parameters*
|===
|Type |Name |Description
| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_events_dispatcher[`Dispatcher`]
a|`$dispatcher`
|
|===


[source%nowrap, php, subs=+macros]
[#getfacetextensions]
----

public getFacetExtensions():link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_facetextensioncontainer_getfacetextensions[`FacetExtensionContainer::getFacetExtensions()`]
====






[source%nowrap, php, subs=+macros]
[#addfacetextension]
----

public addFacetExtension($facetExtension)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_facetextensioncontainer_addfacetextension[`FacetExtensionContainer::addFacetExtension()`]
====






.*Parameters*
|===
|Type |Name |Description
|xref:IO/Services/ItemSearch/Contracts/FacetExtension.adoc#[`FacetExtension`]
a|`$facetExtension`
|
|===


