:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__sortinghelper]]
= SortingHelper



[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper[`SortingHelper`]
====


===== Namespace

`IO\Services\ItemSearch\Helper`






===== Methods

[source%nowrap, php, subs=+macros]
[#getsorting]
----

public getSorting($sortingConfig = null, $isCategory = true):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper_getsorting[`SortingHelper::getSorting()`]
====




Get sorting values from plugin configuration

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$sortingConfig`
|The configuration value from plugin

|link:http://php.net/bool[`bool`^]
a|`$isCategory`
|Get default sorting configuration for category or for search
|===


[source%nowrap, php, subs=+macros]
[#getcategorysorting]
----

public getCategorySorting($sortingConfig = null):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper_getcategorysorting[`SortingHelper::getCategorySorting()`]
====




Get sorting values for categories from config

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$sortingConfig`
|The configuration value
|===


[source%nowrap, php, subs=+macros]
[#getsearchsorting]
----

public getSearchSorting($sortingConfig = null):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper_getsearchsorting[`SortingHelper::getSearchSorting()`]
====




Get sorting values for searches from config

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$sortingConfig`
|The configuration value
|===


[source%nowrap, php, subs=+macros]
[#getuseditemname]
----

public getUsedItemName():link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper_getuseditemname[`SortingHelper::getUsedItemName()`]
====






[source%nowrap, php, subs=+macros]
[#splitpathandorder]
----

public splitPathAndOrder($sorting):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_sortinghelper_splitpathandorder[`SortingHelper::splitPathAndOrder()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$sorting`
|
|===


