:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__itemcolumnbuilder]]
= ItemColumnBuilder





===== Namespace

`IO\Builder\Item`





.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$columnFields`
||link:http://php.net/array[`array`^]
a|`$columnParams`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#defaults]
----

public defaults():xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Get the item data that is used in most scenarios

[source%nowrap, php, subs=+macros]
[#build]
----

public build():link:http://php.net/array[array^]

----





Return generated columns to pass to ItemDataLayerRepository

[source%nowrap, php, subs=+macros]
[#withitembase]
----

public withItemBase($itemBaseFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in ItemBase to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemBaseFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withitemcharacterlist]
----

public withItemCharacterList($itemCharacterFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in ItemCharacterList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemCharacterFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for ItemCharacterList
|===


[source%nowrap, php, subs=+macros]
[#withitemcrosssellinglist]
----

public withItemCrossSellingList($itemCrossSellingListFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in ItemCrossSellingList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemCrossSellingListFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withitemdescription]
----

public withItemDescription($itemDescriptionFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in ItemDescription to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemDescriptionFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for ItemDescription
|===


[source%nowrap, php, subs=+macros]
[#withvariationattributevaluelist]
----

public withVariationAttributeValueList($variationAttributeValueListFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationAttributeValue to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationAttributeValueListFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationbarcode]
----

public withVariationBarcode($variationBarcodeFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationBarcode to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationBarcodeFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationBarcode
|===


[source%nowrap, php, subs=+macros]
[#withvariationbarcodelist]
----

public withVariationBarcodeList($variationBarcodeFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationBarcodeList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationBarcodeFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationbase]
----

public withVariationBase($variationBaseFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationBase to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationBaseFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationbundlecomponentlist]
----

public withVariationBundleComponentList($variationBundleComponentListFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationBundleComponentList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationBundleComponentListFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationcategorylist]
----

public withVariationCategoryList($variationCategoryFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationCategory to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationCategoryFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationimagelist]
----

public withVariationImageList($variationImageListFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationImageList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationImageListFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationlinkmarketplace]
----

public withVariationLinkMarketplace($variationLinkMarketplaceFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationLinkMarketplace to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationLinkMarketplaceFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationlinkwebstore]
----

public withVariationLinkWebstore($variationLinkWebstoreFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationLinkWebstore to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationLinkWebstoreFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationmarketstatus]
----

public withVariationMarketStatus($variationMarketStatusFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationMarketStatus to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationMarketStatusFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationMarketStatus
|===


[source%nowrap, php, subs=+macros]
[#withvariationrecommendedretailprice]
----

public withVariationRecommendedRetailPrice($variationRecommendedPriceFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationRecommendedRetailPrice to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationRecommendedPriceFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationRecommendedRetailPrice
|===


[source%nowrap, php, subs=+macros]
[#withvariationrecommendedretailpricelist]
----

public withVariationRecommendedRetailPriceList($variationRecommendedPriceListFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationRecommendedRetailPriceList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationRecommendedPriceListFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationRecommendedRetailPriceList
|===


[source%nowrap, php, subs=+macros]
[#withvariationretailprice]
----

public withVariationRetailPrice($variationRetailPriceFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationRetailPrice to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationRetailPriceFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationRetailPrice
|===


[source%nowrap, php, subs=+macros]
[#withvariationretailpricelist]
----

public withVariationRetailPriceList($variationRetailPriceListFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationRetailPriceList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationRetailPriceListFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationRetailPriceList
|===


[source%nowrap, php, subs=+macros]
[#withvariationspecialofferretailprice]
----

public withVariationSpecialOfferRetailPrice($variationSpecialOfferRetailPriceFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationSpecialOfferRetailPrice to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationSpecialOfferRetailPriceFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationSpecialOfferRetailPrice
|===


[source%nowrap, php, subs=+macros]
[#withvariationspecialofferretailpricelist]
----

public withVariationSpecialOfferRetailPriceList($variationSpecialOfferRetailPriceListFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationSpecialOfferRetailPriceList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationSpecialOfferRetailPriceListFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationSpecialOfferRetailPriceList
|===


[source%nowrap, php, subs=+macros]
[#withvariationstandardcategory]
----

public withVariationStandardCategory($variationStandardCategoryFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationStandardCategory to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationStandardCategoryFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationStandardCategory
|===


[source%nowrap, php, subs=+macros]
[#withvariationstock]
----

public withVariationStock($variationStockFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationStock to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationStockFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationStock
|===


[source%nowrap, php, subs=+macros]
[#withvariationstockbuffer]
----

public withVariationStockBuffer($variationStockBufferFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationStockBuffer to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationStockBufferFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationStockBuffer
|===


[source%nowrap, php, subs=+macros]
[#withvariationstocklist]
----

public withVariationStockList($variationStockFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationStockList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationStockFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationsupplierlist]
----

public withVariationSupplierList($variationSupplierFields):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationSupplierList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationSupplierFields`
|List of fields
|===


[source%nowrap, php, subs=+macros]
[#withvariationwarehouse]
----

public withVariationWarehouse($variationWarehouseFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationWarehouse to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationWarehouseFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationWarehouse
|===


[source%nowrap, php, subs=+macros]
[#withvariationwarehouselist]
----

public withVariationWarehouseList($variationWarehouseFields, $):xref:IO/Builder/Item/ItemColumnBuilder.adoc#[ItemColumnBuilder]

----





Add fields in VariationWarehouseList to get from ItemDataLayerRepository

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationWarehouseFields`
|List of fields

|xref:IO/Builder/Item/?array.adoc#[`?array`]
a|`$`
|additional params to use for VariationWarehouseList
|===


