:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__itemfilterbuilder]]
= ItemFilterBuilder





===== Namespace

`IO\Builder\Item`





.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$filter`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#build]
----

public build():link:http://php.net/array[array^]

----





Return the generated filters to pass to ItemDataLayerRepository::search

[source%nowrap, php, subs=+macros]
[#hasproperty]
----

public hasProperty($propertyId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by propertyId

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$propertyId`
|
|===


[source%nowrap, php, subs=+macros]
[#hasamazontypeproductgenre]
----

public hasAmazonTypeProductGenre($productGenre):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by amazon product genre

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$productGenre`
|The amazon genre
|===


[source%nowrap, php, subs=+macros]
[#hasattribute]
----

public hasAttribute($attributeIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Deny items not having defined attributes

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$attributeIDs`
|allowed attribute IDs
|===


[source%nowrap, php, subs=+macros]
[#nothasattribute]
----

public notHasAttribute($attributeIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Deny items having one of the defined attributes

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$attributeIDs`
|The attribute IDs to Deny
|===


[source%nowrap, php, subs=+macros]
[#hasagerestriction]
----

public hasAgeRestriction($):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by age restriction

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$`
|List of allowed age restrictions
|===


[source%nowrap, php, subs=+macros]
[#hasamazonproducttype]
----

public hasAmazonProductType($productTypes = []):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by amazon product type. Do not pass any type to filter
items having any amazon product type.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$productTypes`
|The amazon product types to filter
|===


[source%nowrap, php, subs=+macros]
[#nothasamazonproducttype]
----

public notHasAmazonProductType():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Deny items having any amazon product type

[source%nowrap, php, subs=+macros]
[#hasbarcode]
----

public hasBarcode():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items having a barcode

[source%nowrap, php, subs=+macros]
[#nothasbarcode]
----

public notHasBarcode():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items having no barcode

[source%nowrap, php, subs=+macros]
[#hascrossitemid]
----

public hasCrossItemId($itemIDs, $dynamic, $relationship):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by cross selling items

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemIDs`
|The linked item IDs

|link:http://php.net/bool[`bool`^]
a|`$dynamic`
|Filter dynamic entries -> true|false
or all entries -> null

|link:http://php.net/array[`array`^]
a|`$relationship`
|The relationship between the linked items
|===


[source%nowrap, php, subs=+macros]
[#hasid]
----

public hasId($itemIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter item by IDs

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemIDs`
|The item IDs to filter
|===


[source%nowrap, php, subs=+macros]
[#hasimage]
----

public hasImage():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items having an image

[source%nowrap, php, subs=+macros]
[#nothasimage]
----

public notHasImage():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items not having any image

[source%nowrap, php, subs=+macros]
[#hasmarkinone]
----

public hasMarkinOne($markingOneIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by flag 1

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$markingOneIDs`
|IDs of the markings to filter
|===


[source%nowrap, php, subs=+macros]
[#hasmargintwo]
----

public hasMarginTwo($markingTwoIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by flag 2

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$markingTwoIDs`
|IDs of the markings to filter
|===


[source%nowrap, php, subs=+macros]
[#hasproducer]
----

public hasProducer($producerIDs = []):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by manufacturers. Do not pass the manufacturer ID to filter items
not having a manufacturer.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$producerIDs`
|The producers to filter
|===


[source%nowrap, php, subs=+macros]
[#nothasproducer]
----

public notHasProducer():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items not having a manufacturer

[source%nowrap, php, subs=+macros]
[#isbundle]
----

public isBundle():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter bundle items having components

[source%nowrap, php, subs=+macros]
[#notisbundle]
----

public notIsBundle():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Deny bundle items

[source%nowrap, php, subs=+macros]
[#isbundleitem]
----

public isBundleItem():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter bundle components

[source%nowrap, php, subs=+macros]
[#iscolli]
----

public isColli():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items with type &#039;ColliItem&#039;

[source%nowrap, php, subs=+macros]
[#isproductionitem]
----

public isProductionItem():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items with type &#039;ProductionItem&#039;

[source%nowrap, php, subs=+macros]
[#isspecialorderitem]
----

public isSpecialOrderItem():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items with type &#039;DeliveryItem&#039;

[source%nowrap, php, subs=+macros]
[#isstockeditem]
----

public isStockedItem():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items with type &#039;StockedItem&#039;

[source%nowrap, php, subs=+macros]
[#istype]
----

public isType($typeIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by type

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$typeIDs`
|the type IDs
|===


[source%nowrap, php, subs=+macros]
[#isstorespecial]
----

public isStoreSpecial($shopActions):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by store special

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$shopActions`
|IDs of allowed shop actions
|===


[source%nowrap, php, subs=+macros]
[#maybeshippedwithamazonfba]
----

public mayBeShippedWithAmazonFBA():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items which can be shipped via Amazon FBA

[source%nowrap, php, subs=+macros]
[#notmaybeshippedwithamazonfba]
----

public notMayBeShippedWithAmazonFBA()

----





Filter items which cannot be shipped via Amazon FBA

[source%nowrap, php, subs=+macros]
[#wasupdatedbetween]
----

public wasUpdatedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items by last changes on item data

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#descriptioncontains]
----

public descriptionContains($search, $browse):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter itmes containing search string in description

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$search`
|string to search in item description

|link:http://php.net/bool[`bool`^]
a|`$browse`
|use extended search index
|===


[source%nowrap, php, subs=+macros]
[#hasdescription]
----

public hasDescription($lang):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items having a description in a specific language

.*Parameters*
|===
|Type |Name |Description
|xref:IO/Constants/Language.adoc#[`Language`]
a|`$lang`
|the language to use
|===


[source%nowrap, php, subs=+macros]
[#nothasdescription]
----

public notHasDescription($lang):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items not having a description in a specific language

.*Parameters*
|===
|Type |Name |Description
|xref:IO/Constants/Language.adoc#[`Language`]
a|`$lang`
|the language to use
|===


[source%nowrap, php, subs=+macros]
[#haslisting]
----

public hasListing($auctionType):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items linked to a specific listing

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$auctionType`
|Type of listing
|===


[source%nowrap, php, subs=+macros]
[#nothaslisting]
----

public notHasListing($auctionType):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items not linked to a listing

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$auctionType`
|Tyoe of listing
|===


[source%nowrap, php, subs=+macros]
[#variationhasattributes]
----

public variationHasAttributes():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with attributes

[source%nowrap, php, subs=+macros]
[#variationnothasattributes]
----

public variationNotHasAttributes():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations not having an attribute

[source%nowrap, php, subs=+macros]
[#variationhasattributevalue]
----

public variationHasAttributeValue($attributes):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations linked to specific attribute values

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$attributes`
|A Map of attributes: attributeID => attributeValue
|===


[source%nowrap, php, subs=+macros]
[#variationhasattributevaluesets]
----

public variationhasAttributeValueSets($attributeValueSetIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by attribute value sets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$attributeValueSetIDs`
|IDs of attribute value sets
|===


[source%nowrap, php, subs=+macros]
[#variationhasavailability]
----

public variationHasAvailability($availabilityIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by availability

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$availabilityIDs`
|The availability IDs
|===


[source%nowrap, php, subs=+macros]
[#variationhasbarcode]
----

public variationHasBarcode($barcode)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$barcode`
|
|===


[source%nowrap, php, subs=+macros]
[#variationhascustomnumber]
----

public variationHasCustomNumber()

----







[source%nowrap, php, subs=+macros]
[#variationhasexternalid]
----

public variationHasExternalId($externalId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by external variation ID.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$externalId`
|The external ID to filter.
|===


[source%nowrap, php, subs=+macros]
[#variationhasid]
----

public variationHasId($variationIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by variation ID

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$variationIDs`
|The variation IDs
|===


[source%nowrap, php, subs=+macros]
[#variationhasmainwarehouse]
----

public variationHasMainWarehouse($warehouseIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by default warehouse ID

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$warehouseIDs`
|The warehouse IDs
|===


[source%nowrap, php, subs=+macros]
[#variationhassku]
----

public variationHasSKU($itemId, $priceId, $attributeValueSetId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by SKU

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$itemId`
|The Item ID of the SKU

|link:http://php.net/string[`string`^]
a|`$priceId`
|The price ID of the SKU

|link:http://php.net/string[`string`^]
a|`$attributeValueSetId`
|The attribute value set id of the SKU
|===


[source%nowrap, php, subs=+macros]
[#variationhasstocklimitation]
----

public variationHasStockLimitation($stockLimitation):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by stock limitations

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$stockLimitation`
|Allowed stock limitations:
0 -> No stock limitation
1 -> limit net stock
2 -> allow oversold
|===


[source%nowrap, php, subs=+macros]
[#hasunitcombinationid]
----

public hasUnitCombinationId($unitCombinationId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by unit combination

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$unitCombinationId`
|The unit combination id
|===


[source%nowrap, php, subs=+macros]
[#variationisactive]
----

public variationIsActive():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter active variations

[source%nowrap, php, subs=+macros]
[#variationnotisactive]
----

public variationNotIsActive():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter inactive variations

[source%nowrap, php, subs=+macros]
[#variationisprimary]
----

public variationIsPrimary():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Exclude child variations

[source%nowrap, php, subs=+macros]
[#variationischild]
----

public variationIsChild():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Exclude the primary variation

[source%nowrap, php, subs=+macros]
[#onlybasicvariations]
----

public onlyBasicVariations():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





If an item has variations with attributes, exclude variations without attributes.

[source%nowrap, php, subs=+macros]
[#variationwasavailableuntilbetween]
----

public variationWasAvailableUntilBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variation by date &#039;available until&#039;

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationwascreatedbetween]
----

public variationWasCreatedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variation by creation date

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationwasupdatedbetween]
----

public variationWasUpdatedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variation by date of last changes on variation information, e.g. availability

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationwasrelatedupdatedbetween]
----

public variationWasRelatedUpdatedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variation by date of last changes on related data, e.g. category, bundle etc.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationwasreleasedbetween]
----

public variationWasReleasedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by release date

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationhasweight]
----

public variationHasWeight($weightG):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by gross weight

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$weightG`
|Weight in gramm
|===


[source%nowrap, php, subs=+macros]
[#variationhasweighnet]
----

public variationHasWeighNet($weightG):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by net weight

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$weightG`
|Weight in gramm
|===


[source%nowrap, php, subs=+macros]
[#variationhascategory]
----

public variationHasCategory($categoryID):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations linked to a specific category. Do not pass any category
to filter variations linked to any categories.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$categoryID`
|The category ID
|===


[source%nowrap, php, subs=+macros]
[#variationnothascategory]
----

public variationNotHasCategory():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations not linked to a category

[source%nowrap, php, subs=+macros]
[#variationhascategorybranch]
----

public variationHasCategoryBranch($lvl1, $, $, $, $, $):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations linked to a specific category level

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$lvl1`
|Category ID at first layer

|link:http://php.net/int[`int`^]
a|`$`
|?lvl2 Category ID at second layer

|link:http://php.net/int[`int`^]
a|`$`
|?lvl3 Category ID at third layer

|link:http://php.net/int[`int`^]
a|`$`
|?lvl4 Category ID at 4th layer

|link:http://php.net/int[`int`^]
a|`$`
|?lvl5 Category ID at 5th layer

|link:http://php.net/int[`int`^]
a|`$`
|?lvl6 Category ID at 6th layer
|===


[source%nowrap, php, subs=+macros]
[#variationmarkethasadditionalinformation]
----

public variationMarketHasAdditionalInformation($additionalInformation, $marketplaceId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by additional content for specific markets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$additionalInformation`
|

|link:http://php.net/float[`float`^]
a|`$marketplaceId`
|Referred marketplace id
|===


[source%nowrap, php, subs=+macros]
[#variationmarketwasfirstexportedbetween]
----

public variationMarketWasFirstExportedBetween($from, $to, $marketplaceId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by date of first export to specific markets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format

|link:http://php.net/float[`float`^]
a|`$marketplaceId`
|Referred marketplace id
|===


[source%nowrap, php, subs=+macros]
[#variationmarketwaslastexportedbetween]
----

public variationMarketWasLastExportedBetween($from, $to, $marketplaceId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by date of last export to specific markets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format

|link:http://php.net/float[`float`^]
a|`$marketplaceId`
|Referred marketplace idv
|===


[source%nowrap, php, subs=+macros]
[#variationhasshippingprofile]
----

public variationHasShippingProfile($shippingProfileIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by specific shipping profiles

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$shippingProfileIDs`
|List of shipping profile IDs to filter.
|===


[source%nowrap, php, subs=+macros]
[#variationnothasshippingprofile]
----

public variationNotHasShippingProfile($shippingProfileIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations without specific shipping profiles

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$shippingProfileIDs`
|List of shipping profile IDs to deny.
|===


[source%nowrap, php, subs=+macros]
[#variationstockhaswarehouse]
----

public variationStockHasWarehouse($warehouseIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by warehouse

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseIDs`
|"primary", "virtual" or the warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockissalable]
----

public variationStockIsSalable():xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations which are for sale because of stock

[source%nowrap, php, subs=+macros]
[#variationstockhasnet]
----

public variationStockHasNet($warehouseId, $stockConditionOperand, $stockConditionOperator):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by net stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary, "virtual" or the warehouse id

|link:http://php.net/float[`float`^]
a|`$stockConditionOperand`
|stock value to filters

|link:http://php.net/string[`string`^]
a|`$stockConditionOperator`
|the operator to compare stock value
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasnetnegative]
----

public variationStockHasNetNegative($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with negative net stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasnetpositive]
----

public variationStockHasNetPositive($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with positive net stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasnetequalzero]
----

public variationStockHasNetEqualZero($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with net stock value of 0

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasphysical]
----

public variationStockHasPhysical($warehouseId, $stockConditionOperand, $stockConditionOperator):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with phyiscal stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id

|link:http://php.net/float[`float`^]
a|`$stockConditionOperand`
|stock value to filters

|link:http://php.net/string[`string`^]
a|`$stockConditionOperator`
|the operator to compare stock value
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasphysicalnegative]
----

public variationStockHasPhysicalNegative($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with negative physical stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasphysicalpositive]
----

public variationStockHasPhysicalPositive($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with positive physical stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasphysicalequalzero]
----

public variationStockHasPhysicalEqualZero($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations with physical stock value of 0

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockhasreorderlevel]
----

public variationStockHasReorderLevel($warehouseId, $stockConditionOperand, $stockConditionOperator):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by reorder level

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id

|link:http://php.net/float[`float`^]
a|`$stockConditionOperand`
|stock value to filters

|link:http://php.net/string[`string`^]
a|`$stockConditionOperator`
|the operator to compare stock value
|===


[source%nowrap, php, subs=+macros]
[#variationstockisreorderlevelreached]
----

public variationStockIsReorderLevelReached($warehouseId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations fallen below reorder level

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/mixed[`mixed`^]
a|`$warehouseId`
|"primary", "virtual" or warehouse id
|===


[source%nowrap, php, subs=+macros]
[#variationstockwasupdatedbetween]
----

public variationStockWasUpdatedBetween($from, $to):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by date of last changes to stock

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$from`
|The start datetime of the period in unix format

|link:http://php.net/string[`string`^]
a|`$to`
|The end datetime of the period in unix format
|===


[source%nowrap, php, subs=+macros]
[#variationhassupplier]
----

public variationHasSupplier($supplierIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by specific supplier

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$supplierIDs`
|Supplier IDs to filter.
|===


[source%nowrap, php, subs=+macros]
[#variationnothassupplier]
----

public variationNotHasSupplier($supplierIDs):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations not having a specific supplier

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$supplierIDs`
|Supplier IDs to deny.
|===


[source%nowrap, php, subs=+macros]
[#variationhassuppliernumber]
----

public variationHasSupplierNumber($supplierNumber):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter variations by supplier number

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$supplierNumber`
|the supplier number
|===


[source%nowrap, php, subs=+macros]
[#variationisvisibleformarketplace]
----

public variationIsVisibleForMarketplace($mandatoryAllMarketplace, $mandatoryOneMarketplace):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items which are visible for specific markets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$mandatoryAllMarketplace`
|All listed marketplaces have to be linked with filtered item.

|link:http://php.net/array[`array`^]
a|`$mandatoryOneMarketplace`
|At least one marketplace have to be linked with filtered item.
|===


[source%nowrap, php, subs=+macros]
[#variationnotisvisibleformarketplace]
----

public variationNotIsVisibleForMarketplace($mandatoryAllMarketplace, $mandatoryOneMarketplace):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items which are not visible for specific markets

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$mandatoryAllMarketplace`
|All listed marketplaces have to be linked with filtered item.

|link:http://php.net/array[`array`^]
a|`$mandatoryOneMarketplace`
|At least one marketplace have to be linked with filtered item.
|===


[source%nowrap, php, subs=+macros]
[#variationisvisibleforplentyid]
----

public variationIsVisibleForPlentyId($mandatoryAllPlentyId, $mandatoryOnePlentyId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items which are visible for specific client (store)

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$mandatoryAllPlentyId`
|All listed shops have to be linked with filtered item.

|link:http://php.net/array[`array`^]
a|`$mandatoryOnePlentyId`
|At least one shop has to be linked with filtered item.
|===


[source%nowrap, php, subs=+macros]
[#variationnotisvisibleforplentyid]
----

public variationNotIsVisibleForPlentyId($mandatoryAllPlentyId, $mandatoryOnePlentyId):xref:IO/Builder/Item/ItemFilterBuilder.adoc#[ItemFilterBuilder]

----





Filter items which are not visible for specific client (store)

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$mandatoryAllPlentyId`
|All listed shops have to be linked with filtered item.

|link:http://php.net/array[`array`^]
a|`$mandatoryOnePlentyId`
|At least one shop has to be linked with filtered item.
|===


[source%nowrap, php, subs=+macros]
[#variationhasretailprice]
----

public variationHasRetailPrice()

----







