:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__checkoutservice]]
= CheckoutService

This service class contains methods for manipulating the checkout. +
All public functions are available in the Twig template renderer.



===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendpaymentmethodrepositorycontract[`FrontendPaymentMethodRepositoryContract`]
a|`$frontendPaymentMethodRepository`
|This repository exposes functionality related to payment methods|xref:stable7@interface::Frontend.adoc#frontend_contracts_checkout[`Checkout`]
a|`$checkout`
||xref:stable7@interface::Basket.adoc#basket_contracts_basketrepositorycontract[`BasketRepositoryContract`]
a|`$basketRepository`
||xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendsessionstoragefactorycontract[`FrontendSessionStorageFactoryContract`]
a|`$sessionStorage`
||xref:IO/Services/CustomerService.adoc#[`CustomerService`]
a|`$customerService`
||xref:stable7@interface::Order.adoc#order_contracts_parcelservicepresetrepositorycontract[`ParcelServicePresetRepositoryContract`]
a|`$parcelServicePresetRepo`
||xref:stable7@interface::Frontend.adoc#frontend_contracts_currencyexchangerepositorycontract[`CurrencyExchangeRepositoryContract`]
a|`$currencyExchangeRepo`
||xref:IO/Services/BasketService.adoc#[`BasketService`]
a|`$basketService`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
a|`$sessionStorageRepository`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract[`WebstoreConfigurationRepositoryContract`]
a|`$webstoreConfigurationRepository`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_checkoutrepositorycontract[`CheckoutRepositoryContract`]
a|`$checkoutRepository`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$contactRepository`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$cache`
||link:http://php.net/string[`string`^]
a|`$pluginNamespace`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($frontendPaymentMethodRepository, $checkout, $basketRepository, $sessionStorage, $customerService, $parcelServicePresetRepo, $currencyExchangeRepo, $basketService, $sessionStorageRepository, $webstoreConfigurationRepository, $dispatcher, $checkoutRepository, $contactRepository)

----





CheckoutService constructor.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendpaymentmethodrepositorycontract[`FrontendPaymentMethodRepositoryContract`]
a|`$frontendPaymentMethodRepository`
|

|xref:stable7@interface::Frontend.adoc#frontend_contracts_checkout[`Checkout`]
a|`$checkout`
|

|xref:stable7@interface::Basket.adoc#basket_contracts_basketrepositorycontract[`BasketRepositoryContract`]
a|`$basketRepository`
|

|xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendsessionstoragefactorycontract[`FrontendSessionStorageFactoryContract`]
a|`$sessionStorage`
|

|xref:IO/Services/CustomerService.adoc#[`CustomerService`]
a|`$customerService`
|

|xref:stable7@interface::Order.adoc#order_contracts_parcelservicepresetrepositorycontract[`ParcelServicePresetRepositoryContract`]
a|`$parcelServicePresetRepo`
|

|xref:stable7@interface::Frontend.adoc#frontend_contracts_currencyexchangerepositorycontract[`CurrencyExchangeRepositoryContract`]
a|`$currencyExchangeRepo`
|

|xref:IO/Services/BasketService.adoc#[`BasketService`]
a|`$basketService`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
a|`$sessionStorageRepository`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract[`WebstoreConfigurationRepositoryContract`]
a|`$webstoreConfigurationRepository`
|

| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_events_dispatcher[`Dispatcher`]
a|`$dispatcher`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_checkoutrepositorycontract[`CheckoutRepositoryContract`]
a|`$checkoutRepository`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$contactRepository`
|
|===


[source%nowrap, php, subs=+macros]
[#getcheckout]
----

public getCheckout($retry = true):link:http://php.net/array[array^]

----





Get the relevant data for the checkout.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$retry`
|Try loading checkout again on failure (e.g. problems during calculating totals)
|===


[source%nowrap, php, subs=+macros]
[#getcurrency]
----

public getCurrency():link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_checkoutrepositorycontract_getcurrency[`CheckoutRepositoryContract::getCurrency()`]
====




Get the current currency from the session.

[source%nowrap, php, subs=+macros]
[#setcurrency]
----

public setCurrency($currency)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_checkoutrepositorycontract_setcurrency[`CheckoutRepositoryContract::setCurrency()`]
====




Set the current currency in the session.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$currency`
|The currency to be used.
|===


[source%nowrap, php, subs=+macros]
[#getcurrencylist]
----

public getCurrencyList():link:http://php.net/array[array^]

----





Get array with all active currencies.

[source%nowrap, php, subs=+macros]
[#getcurrencydata]
----

public getCurrencyData():link:http://php.net/array[array^]

----





Get the name and the symbol for the currently selected currency.

[source%nowrap, php, subs=+macros]
[#getcurrencypattern]
----

public getCurrencyPattern():link:http://php.net/array[array^]

----





Get all required information about how to display monetary values.

[source%nowrap, php, subs=+macros]
[#getmethodofpaymentid]
----

public getMethodOfPaymentId():link:http://php.net/int[int^]

----





Get the id of the current payment method.

[source%nowrap, php, subs=+macros]
[#setmethodofpaymentid]
----

public setMethodOfPaymentId($methodOfPaymentID)

----





Set the id of the current payment method.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$methodOfPaymentID`
|Id of the method of payment to be used.
|===


[source%nowrap, php, subs=+macros]
[#preparepayment]
----

public preparePayment():link:http://php.net/array[array^]

----





Prepare the payment.

[source%nowrap, php, subs=+macros]
[#getmethodofpaymentlist]
----

public getMethodOfPaymentList():link:http://php.net/array[array^]

----





List all available payment methods.

[source%nowrap, php, subs=+macros]
[#getmethodofpaymentexpresscheckoutlist]
----

public getMethodOfPaymentExpressCheckoutList():link:http://php.net/array[array^]

----





List all payment methods available for express checkout.

[source%nowrap, php, subs=+macros]
[#getcheckoutpaymentdatalist]
----

public getCheckoutPaymentDataList():link:http://php.net/array[array^]

----





Get a list of the payment method data.

[source%nowrap, php, subs=+macros]
[#getshippingprofilelist]
----

public getShippingProfileList():link:http://php.net/array[array^]

----





Get the list of available shipping profiles.

[source%nowrap, php, subs=+macros]
[#getshippingcountryid]
----

public getShippingCountryId():link:http://php.net/int[int^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_checkoutrepositorycontract_getshippingcountryid[`CheckoutRepositoryContract::getShippingCountryId()`]
====




Get the ID of the current shipping country

[source%nowrap, php, subs=+macros]
[#setshippingcountryid]
----

public setShippingCountryId($shippingCountryId)

----





Set the id of the current shipping country.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$shippingCountryId`
|Id of the shipping country to select.
|===


[source%nowrap, php, subs=+macros]
[#getshippingprofileid]
----

public getShippingProfileId():link:http://php.net/int[int^]

----





Get the ID of the current shipping profile.

[source%nowrap, php, subs=+macros]
[#setshippingprofileid]
----

public setShippingProfileId($shippingProfileId)

----





Set the ID of the current shipping profile.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$shippingProfileId`
|Id of the shipping profile to select.
|===


[source%nowrap, php, subs=+macros]
[#getdeliveryaddressid]
----

public getDeliveryAddressId():link:http://php.net/int[int^]

----





Get the ID of the current delivery address.

[source%nowrap, php, subs=+macros]
[#setdeliveryaddressid]
----

public setDeliveryAddressId($deliveryAddressId)

----





Set the ID of the current delivery address.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$deliveryAddressId`
|Id of the address to be used as delivery address when creating an order.
|===


[source%nowrap, php, subs=+macros]
[#getbillingaddressid]
----

public getBillingAddressId():link:http://php.net/int[int^]

----





Get the ID of the current invoice address.

[source%nowrap, php, subs=+macros]
[#setbillingaddressid]
----

public setBillingAddressId($billingAddressId)

----





Set the ID of the current invoice address.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$billingAddressId`
|Id of the address to be used as billing address when creating an order.
|===


[source%nowrap, php, subs=+macros]
[#setdefaultshippingcountryid]
----

public setDefaultShippingCountryId()

----





Reset the current shipping country to the default defined in the webstore configuration.

[source%nowrap, php, subs=+macros]
[#getmaxdeliverydays]
----

public getMaxDeliveryDays():link:http://php.net/array[array^]

----





Get the maximum days of delivery for each shipping profile.

[source%nowrap, php, subs=+macros]
[#setreadonlycheckout]
----

public setReadOnlyCheckout($readonly)

----





Set the checkout to be readonly.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$readonly`
|Enable/disable readonly mode for checkout.
|===


[source%nowrap, php, subs=+macros]
[#getreadonlycheckout]
----

public getReadOnlyCheckout():link:http://php.net/bool[bool^]

----





Check if checkout should display data from external checkout processes in readonly mode.

[source%nowrap, php, subs=+macros]
[#getcontactwish]
----

public getContactWish():link:http://php.net/string[string^]

----





Returns the given contact wish from session.

[source%nowrap, php, subs=+macros]
[#frommemorycache]
----

public fromMemoryCache()

----







[source%nowrap, php, subs=+macros]
[#resetmemorycache]
----

public resetMemoryCache($key = null)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$key`
|
|===


