:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__customerservice]]
= CustomerService

This service class contains functions related to the customer. +
All public functions are available in the Twig template renderer.



===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|xref:stable7@interface::Account.adoc#account_contracts_contactaccountrepositorycontract[`ContactAccountRepositoryContract`]
a|`$accountRepository`
||xref:stable7@interface::Account.adoc#account_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$coreContactRepository`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$contactRepository`
||xref:stable7@interface::Account.adoc#account_contracts_contactaddressrepositorycontract[`ContactAddressRepositoryContract`]
a|`$contactAddressRepository`
||xref:stable7@interface::Account.adoc#account_contracts_addressrepositorycontract[`AddressRepositoryContract`]
a|`$addressRepository`
||xref:stable7@interface::Account.adoc#account_contracts_contactclassrepositorycontract[`ContactClassRepositoryContract`]
a|`$contactClassRepository`
||xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
a|`$sessionStorageRepository`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$cache`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($accountRepository, $coreContactRepository, $contactRepository, $contactAddressRepository, $addressRepository, $contactClassRepository, $sessionStorageRepository)

----





CustomerService constructor.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Account.adoc#account_contracts_contactaccountrepositorycontract[`ContactAccountRepositoryContract`]
a|`$accountRepository`
|

|xref:stable7@interface::Account.adoc#account_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$coreContactRepository`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract[`ContactRepositoryContract`]
a|`$contactRepository`
|

|xref:stable7@interface::Account.adoc#account_contracts_contactaddressrepositorycontract[`ContactAddressRepositoryContract`]
a|`$contactAddressRepository`
|

|xref:stable7@interface::Account.adoc#account_contracts_addressrepositorycontract[`AddressRepositoryContract`]
a|`$addressRepository`
|

|xref:stable7@interface::Account.adoc#account_contracts_contactclassrepositorycontract[`ContactClassRepositoryContract`]
a|`$contactClassRepository`
|

|xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
a|`$sessionStorageRepository`
|
|===


[source%nowrap, php, subs=+macros]
[#getcontactid]
----

public getContactId():link:http://php.net/int[int^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract_getcontactid[`ContactRepositoryContract::getContactId()`]
====




Get the ID of the current contact from the session

[source%nowrap, php, subs=+macros]
[#getcontactclassdata]
----

public getContactClassData($contactClassId):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract_getcontactclassdata[`ContactRepositoryContract::getContactClassData()`]
====




Get the data of a contact class

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$contactClassId`
|Unique id of a contact class
|===


[source%nowrap, php, subs=+macros]
[#shownetprices]
----

public showNetPrices():link:http://php.net/bool[bool^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract_shownetprices[`ContactRepositoryContract::showNetPrices()`]
====




Check if net prices should be shown

[source%nowrap, php, subs=+macros]
[#shownetpricesbycontactid]
----

public showNetPricesByContactId($contactId):link:http://php.net/bool[bool^]

----





Check if net prices should be shown for this contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$contactId`
|Unique id of a contact
|===


[source%nowrap, php, subs=+macros]
[#getcontactclassminimumorderquantity]
----

public getContactClassMinimumOrderQuantity():link:http://php.net/int[int^]

----





Gets the minimum order quantity of the current contacts contact class

[source%nowrap, php, subs=+macros]
[#registercustomer]
----

public registerCustomer($contactData, $billingAddressData = [], $deliveryAddressData = []):xref:stable7@interface::Account.adoc#account_models_contact[Contact]

----





Create a contact with addresses if specified

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$contactData`
|The contacts data

|link:http://php.net/array[`array`^]
a|`$billingAddressData`
|The contacts billing address

|link:http://php.net/array[`array`^]
a|`$deliveryAddressData`
|The contacts delivery address
|===


[source%nowrap, php, subs=+macros]
[#createaccount]
----

public createAccount($accountData):xref:stable7@interface::Account.adoc#account_models_account[Account]

----





Creates an user account

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$accountData`
|User account data
|===


[source%nowrap, php, subs=+macros]
[#createcontact]
----

public createContact($contactData):xref:stable7@interface::Account.adoc#account_models_contact[Contact] \| link:http://php.net/array[array^]

----





Create a new contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$contactData`
|The contacts data
|===


[source%nowrap, php, subs=+macros]
[#getcontact]
----

public getContact():xref:stable7@interface::Account.adoc#account_models_contact[Contact]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract_getcontact[`ContactRepositoryContract::getContact()`]
====




Find the current contact

[source%nowrap, php, subs=+macros]
[#getcontactclassid]
----

public getContactClassId():link:http://php.net/int[int^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_contactrepositorycontract_getcontactclassid[`ContactRepositoryContract::getContactClassId()`]
====




Gets the current contact&#039;s contact class id

[source%nowrap, php, subs=+macros]
[#updatecontact]
----

public updateContact($contactData):xref:stable7@interface::Account.adoc#account_models_contact[Contact]

----





Update a contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$contactData`
|New contact data
|===


[source%nowrap, php, subs=+macros]
[#updatepassword]
----

public updatePassword($newPassword, $contactId, $hash = &quot;&quot;):link:http://php.net/mixed[mixed^]

----





Update a customers password

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$newPassword`
|The new password

|link:http://php.net/int[`int`^]
a|`$contactId`
|Id of the contact

|link:http://php.net/string[`string`^]
a|`$hash`
|Optional: Security hash
|===


[source%nowrap, php, subs=+macros]
[#getaddresses]
----

public getAddresses($typeId = null):link:http://php.net/array[array^] \| xref:IO/Services/Illuminate/Database/Eloquent/Collection.adoc#[Collection]

----





List the addresses of a contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$typeId`
|Type of address
|===


[source%nowrap, php, subs=+macros]
[#getaddress]
----

public getAddress($addressId, $typeId):xref:stable7@interface::Account.adoc#account_models_address[Address]

----





Get an address by ID

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$addressId`
|Unique id of address

|link:http://php.net/int[`int`^]
a|`$typeId`
|Type of address
|===


[source%nowrap, php, subs=+macros]
[#createaddress]
----

public createAddress($addressData, $typeId):xref:stable7@interface::Account.adoc#account_models_address[Address]

----





Create an address with the specified address type

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$addressData`
|The address data

|link:http://php.net/int[`int`^]
a|`$typeId`
|Type of address
|===


[source%nowrap, php, subs=+macros]
[#updateaddress]
----

public updateAddress($addressId, $addressData, $typeId):xref:stable7@interface::Account.adoc#account_models_address[Address]

----





Update an address

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$addressId`
|Id of address to update

|link:http://php.net/array[`array`^]
a|`$addressData`
|Updated address data

|link:http://php.net/int[`int`^]
a|`$typeId`
|Type of address to update
|===


[source%nowrap, php, subs=+macros]
[#deleteaddress]
----

public deleteAddress($addressId, $typeId)

----





Delete an address

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$addressId`
|Id of address to delete

|link:http://php.net/int[`int`^]
a|`$typeId`
|Type of address to delete
|===


[source%nowrap, php, subs=+macros]
[#getorders]
----

public getOrders($page = 1, $items = 10, $filters = []):link:http://php.net/array[array^] \| xref:IO/Services/Plenty/Repositories/Models/PaginatedResult.adoc#[PaginatedResult]

----





Get a list of orders for the current contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$page`
|Optional: What page to get

|link:http://php.net/int[`int`^]
a|`$items`
|Optional: How many items per page

|link:http://php.net/array[`array`^]
a|`$filters`
|Optional: Additional filters
|===


[source%nowrap, php, subs=+macros]
[#hasreturns]
----

public hasReturns():link:http://php.net/bool[bool^]

----





Check if a contact has made return orders

[source%nowrap, php, subs=+macros]
[#getreturns]
----

public getReturns($page = 1, $items = 10, $filters = [], $wrapped = true):xref:IO/Services/Plenty/Repositories/Models/PaginatedResult.adoc#[PaginatedResult]

----





Get a list of return orders for the current contact

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$page`
|

|link:http://php.net/int[`int`^]
a|`$items`
|

|link:http://php.net/array[`array`^]
a|`$filters`
|

|link:http://php.net/bool[`bool`^]
a|`$wrapped`
|
|===


[source%nowrap, php, subs=+macros]
[#getlatestorder]
----

public getLatestOrder():xref:IO/Models/LocalizedOrder.adoc#[LocalizedOrder]

----





Get the last order created by the current contact

[source%nowrap, php, subs=+macros]
[#resetguestaddresses]
----

public resetGuestAddresses()

----





Resets the baskets current addresses if current contact is a guest

[source%nowrap, php, subs=+macros]
[#getemail]
----

public getEmail():link:http://php.net/string[string^]

----





Gets the email address of the current contact

[source%nowrap, php, subs=+macros]
[#getcontactnumber]
----

public getContactNumber($contactId):link:http://php.net/string[string^]

----





Gets a contacts contact number

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$contactId`
|Unique id of a contact
|===


[source%nowrap, php, subs=+macros]
[#deleteguestaddresses]
----

public deleteGuestAddresses()

----





Delete adresses that are not bound to a contact

[source%nowrap, php, subs=+macros]
[#frommemorycache]
----

public fromMemoryCache()

----







[source%nowrap, php, subs=+macros]
[#resetmemorycache]
----

public resetMemoryCache($key = null)

----







.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$key`
|
|===


