:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__itemwishlistservice]]
= ItemWishListService

This service class contains functions related to the customers wish list. +
All public functions are available in the Twig template renderer.



===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|link:http://php.net/mixed[`mixed`^]
a|`$itemWishListRepo`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($sessionStorageRepositoryContract)

----





ItemWishListService constructor.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
a|`$sessionStorageRepositoryContract`
|
|===


[source%nowrap, php, subs=+macros]
[#additemwishlistentry]
----

public addItemWishListEntry($variationId, $quantity):link:http://php.net/mixed[mixed^]

----





Add a variation to the wish list

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|An variation id

|link:http://php.net/int[`int`^]
a|`$quantity`
|The desired quantity of the variation
|===


[source%nowrap, php, subs=+macros]
[#isiteminwishlist]
----

public isItemInWishList($variationId):link:http://php.net/bool[bool^]

----





Check if a variation is in the wish list

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|An variation id
|===


[source%nowrap, php, subs=+macros]
[#getitemwishlist]
----

public getItemWishList():link:http://php.net/array[array^]

----





Get a list of all variation ids in the wish list

[source%nowrap, php, subs=+macros]
[#getcounteditemwishlist]
----

public getCountedItemWishList():link:http://php.net/int[int^]

----





Get number of entries in wish list

[source%nowrap, php, subs=+macros]
[#removeitemwishlistentry]
----

public removeItemWishListEntry($variationId):link:http://php.net/bool[bool^]

----





Remove a variation from the wish list

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$variationId`
|An variation id
|===


[source%nowrap, php, subs=+macros]
[#migrateguestitemwishlist]
----

public migrateGuestItemWishList()

----





Migrates a guest wish list into a contacts wish list.

