:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__legalinformationservice]]
= LegalInformationService

This service class contains functions related to the legal information widgets. +
All public functions are available in the Twig template renderer.



===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$legalInformationRepo`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$lang`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$plentyId`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($legalInformationRepo, $app)

----





LegalInformationService constructor.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Frontend.adoc#frontend_contracts_legalinformationrepositorycontract[`LegalInformationRepositoryContract`]
a|`$legalInformationRepo`
|

| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_plugin_application[`Application`]
a|`$app`
|
|===


[source%nowrap, php, subs=+macros]
[#gettermsandconditions]
----

public getTermsAndConditions():xref:stable7@interface::Frontend.adoc#frontend_models_legalinformation[LegalInformation]

----





Get the LegalInformation model for the Terms and Conditions

[source%nowrap, php, subs=+macros]
[#getcancellationrights]
----

public getCancellationRights():xref:stable7@interface::Frontend.adoc#frontend_models_legalinformation[LegalInformation]

----





Get the LegalInformation model for the Cancellation Rights

[source%nowrap, php, subs=+macros]
[#getprivacypolicy]
----

public getPrivacyPolicy():xref:stable7@interface::Frontend.adoc#frontend_models_legalinformation[LegalInformation]

----





Get the LegalInformation model for the Privacy Policy

[source%nowrap, php, subs=+macros]
[#getlegaldisclosure]
----

public getLegalDisclosure():xref:stable7@interface::Frontend.adoc#frontend_models_legalinformation[LegalInformation]

----





Get the LegalInformation model for the Legal Disclosure

[source%nowrap, php, subs=+macros]
[#getwithdrawalform]
----

public getWithdrawalForm():xref:stable7@interface::Frontend.adoc#frontend_models_legalinformation[LegalInformation]

----





Get the LegalInformation model for the Withdrawal Form

