:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__sessionstorageservice]]
= SessionStorageService

This service class contains functions related to storing and reading data in the session. +
All public functions are available in the Twig template renderer.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract[`SessionStorageRepositoryContract`]
====


===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[`string`^]
a|`$language`
||xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendsessionstoragefactorycontract[`FrontendSessionStorageFactoryContract`]
a|`$sessionStorage`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($sessionStorage)

----





SessionStorageService constructor.

.*Parameters*
|===
|Type |Name |Description
|xref:stable7@interface::Frontend.adoc#frontend_contracts_frontendsessionstoragefactorycontract[`FrontendSessionStorageFactoryContract`]
a|`$sessionStorage`
|
|===


[source%nowrap, php, subs=+macros]
[#setsessionvalue]
----

public setSessionValue($name, $value)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract_setsessionvalue[`SessionStorageRepositoryContract::setSessionValue()`]
====




Set the value in the session

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$name`
|Name/Key of the value

|link:http://php.net/mixed[`mixed`^]
a|`$value`
|The value to be stored
|===


[source%nowrap, php, subs=+macros]
[#getsessionvalue]
----

public getSessionValue($name):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract_getsessionvalue[`SessionStorageRepositoryContract::getSessionValue()`]
====




Get a value from the session

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$name`
|Name/Key of the value
|===


[source%nowrap, php, subs=+macros]
[#getlang]
----

public getLang():link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_localizationrepositorycontract_getlanguage[`LocalizationRepositoryContract::getLanguage()`]
====




Get the language from session

[source%nowrap, php, subs=+macros]
[#getcustomer]
----

public getCustomer():xref:stable7@interface::Frontend.adoc#frontend_models_customer[Customer]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_sessionstoragerepositorycontract_getcustomer[`SessionStorageRepositoryContract::getCustomer()`]
====




Gets the model for the current customer from the session

