:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__templateservice]]
= TemplateService

This service class contains functions related to templating functionality. +
All public functions are available in the Twig template renderer.



===== Namespace

`IO\Services`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[`string`^]
a|`$currentTemplate`
|Stores the id of the current template|link:http://php.net/array[`array`^]
a|`$currentTemplateData`
|Stores data for the current template|link:http://php.net/bool[`bool`^]
a|`$shouldBeCached`
|If true, template will be cached in the content cache (Default: true)|link:http://php.net/bool[`bool`^]
a|`$forceNoIndex`
|If true, force the NOINDEX robots attribute for this template
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#forcenoindex]
----

public forceNoIndex($forceNoIndex)

----





Setter for the $forceNoIndex property.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$forceNoIndex`
|If true, force the NOINDEX robots attribute for this template.
|===


[source%nowrap, php, subs=+macros]
[#isnoindexforced]
----

public isNoIndexForced():link:http://php.net/bool[bool^]

----





Getter for the $forceNoIndex property. If true, force the NOINDEX robots attribute for this template.

[source%nowrap, php, subs=+macros]
[#shouldbecached]
----

public shouldBeCached():link:http://php.net/bool[bool^]

----





Getter for the $shouldBeCached property. If true, template will be cached in the content cache

[source%nowrap, php, subs=+macros]
[#disablecachefortemplate]
----

public disableCacheForTemplate()

----





Disable the content caching for this template

[source%nowrap, php, subs=+macros]
[#getcurrenttemplate]
----

public getCurrentTemplate():link:http://php.net/string[string^]

----





Getter for the $currentTemplate property. Returns the id of the current template.

[source%nowrap, php, subs=+macros]
[#setcurrenttemplate]
----

public setCurrentTemplate($template)

----





Setter for the $currentTemplate property.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$template`
|Identifier of a template
|===


[source%nowrap, php, subs=+macros]
[#iscurrenttemplate]
----

public isCurrentTemplate($templateToCheck):link:http://php.net/bool[bool^]

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is() instead

====




Check if the current template is same as the parameter

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$templateToCheck`
|A template id to compare against
|===


[source%nowrap, php, subs=+macros]
[#ishome]
----

public isHome()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::HOME) instead

====




Check if the current template is the home template

[source%nowrap, php, subs=+macros]
[#isitem]
----

public isItem()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::ITEM) instead

====




Check if the current template is the item template

[source%nowrap, php, subs=+macros]
[#ismyaccount]
----

public isMyAccount()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::MY_ACCOUNT) instead

====




Check if the current template is the my account template

[source%nowrap, php, subs=+macros]
[#ischeckout]
----

public isCheckout()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::CHECKOUT) instead

====




Check if the current template is the checkout template

[source%nowrap, php, subs=+macros]
[#issearch]
----

public isSearch()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::SEARCH) instead

====




Check if the current template is the search template

[source%nowrap, php, subs=+macros]
[#iscategory]
----

public isCategory()

----

[WARNING]
.Deprecated! 
====

Use ShopUrls::is(RouteConfig::CATEGORY) instead

====




Check if the current template is the category template

[source%nowrap, php, subs=+macros]
[#rendertemplate]
----

public renderTemplate($template, $params):link:http://php.net/string[string^]

----





Render a twig template into a string

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$template`
|A twig template to render

|link:http://php.net/array[`array`^]
a|`$params`
|Environmental data for the twig template
|===


[source%nowrap, php, subs=+macros]
[#ischeapestsorting]
----

public isCheapestSorting():link:http://php.net/bool[bool^]

----





Check if the price sorting returns the cheapest price

