:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__webstoreconfigurationservice]]
= WebstoreConfigurationService

This service class contains functions for getting data from the webstore configuration. +
All public functions are available in the Twig template renderer.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract[`WebstoreConfigurationRepositoryContract`]
====


===== Namespace

`IO\Services`






===== Methods

[source%nowrap, php, subs=+macros]
[#getplentyid]
----

public getPlentyId()

----

[WARNING]
.Deprecated! 
====

since 4.3.0

see:xref:IO/Helper/Utils.adoc#getplentyid[`Utils::getPlentyId()`]
====




Get the plentyId

[source%nowrap, php, subs=+macros]
[#getwebstoreconfig]
----

public getWebstoreConfig()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getwebstoreconfiguration[`WebstoreConfigurationRepositoryContract::getWebstoreConfiguration()`]
====




Get the webstore configuraion

[source%nowrap, php, subs=+macros]
[#getactivelanguagelist]
----

public getActiveLanguageList()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getactivelanguagelist[`WebstoreConfigurationRepositoryContract::getActiveLanguageList()`]
====




Get the activate languages of the webstore

[source%nowrap, php, subs=+macros]
[#getdefaultlanguage]
----

public getDefaultLanguage()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getdefaultlanguage[`WebstoreConfigurationRepositoryContract::getDefaultLanguage()`]
====




Get the default language of the webstore

[source%nowrap, php, subs=+macros]
[#getdefaultparcelserviceid]
----

public getDefaultParcelServiceId()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getdefaultparcelserviceid[`WebstoreConfigurationRepositoryContract::getDefaultParcelServiceId()`]
====




Get the default parcel-service-id of the webstore

[source%nowrap, php, subs=+macros]
[#getdefaultparcelservicepresetid]
----

public getDefaultParcelServicePresetId()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getdefaultparcelservicepresetid[`WebstoreConfigurationRepositoryContract::getDefaultParcelServicePresetId()`]
====




Get the default parcel-service-preset-id of the webstore

[source%nowrap, php, subs=+macros]
[#getdefaultshippingcountryid]
----

public getDefaultShippingCountryId()

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_webstoreconfigurationrepositorycontract_getdefaultshippingcountryid[`WebstoreConfigurationRepositoryContract::getDefaultShippingCountryId()`]
====




Get the default shipping-country-id of the webstore

