:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__urlquery]]
= UrlQuery



[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery[`UrlQuery`]
====


===== Namespace

`IO\Services\UrlBuilder`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$domain`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$path`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$lang`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#shouldappendtrailingslash]
----

public static shouldAppendTrailingSlash():link:http://php.net/bool[bool^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_shouldappendtrailingslash[`UrlQuery::shouldAppendTrailingSlash()`]
====






[source%nowrap, php, subs=+macros]
[#__construct]
----

public __construct($path = null, $lang = null)

----





UrlQuery constructor.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$path`
|

|link:http://php.net/string[`string`^]
a|`$lang`
|
|===


[source%nowrap, php, subs=+macros]
[#append]
----

public append($suffix):xref:IO/Services/UrlBuilder/UrlQuery.adoc#[UrlQuery]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_append[`UrlQuery::append()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$suffix`
|
|===


[source%nowrap, php, subs=+macros]
[#join]
----

public join($path):xref:IO/Services/UrlBuilder/UrlQuery.adoc#[UrlQuery]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_join[`UrlQuery::join()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$path`
|
|===


[source%nowrap, php, subs=+macros]
[#toabsoluteurl]
----

public toAbsoluteUrl($includeLanguage = false):link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_toabsoluteurl[`UrlQuery::toAbsoluteUrl()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$includeLanguage`
|
|===


[source%nowrap, php, subs=+macros]
[#torelativeurl]
----

public toRelativeUrl($includeLanguage = false):link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_torelativeurl[`UrlQuery::toRelativeUrl()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$includeLanguage`
|
|===


[source%nowrap, php, subs=+macros]
[#getpath]
----

public getPath($includeLanguage = false):link:http://php.net/mixed[mixed^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_getpath[`UrlQuery::getPath()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$includeLanguage`
|
|===


[source%nowrap, php, subs=+macros]
[#equals]
----

public equals($path):link:http://php.net/bool[bool^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_helpers_urlquery_equals[`UrlQuery::equals()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$path`
|
|===


