:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__variationurlbuilder]]
= VariationUrlBuilder



[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_urlbuilderrepositorycontract[`UrlBuilderRepositoryContract`]
====


===== Namespace

`IO\Services\UrlBuilder`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$urlPathMap`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$requestedItems`
||link:http://php.net/string[`string`^]
a|`$pluginNamespace`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#fillitemurl]
----

public static fillItemUrl($itemData)

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_urlbuilderrepositorycontract_fillitemurl[`UrlBuilderRepositoryContract::fillItemUrl()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$itemData`
|
|===


[source%nowrap, php, subs=+macros]
[#buildurl]
----

public buildUrl($itemId, $variationId, $lang = null):xref:IO/Services/UrlBuilder/UrlQuery.adoc#[UrlQuery]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_urlbuilderrepositorycontract_buildvariationurl[`UrlBuilderRepositoryContract::buildVariationUrl()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|

|link:http://php.net/int[`int`^]
a|`$variationId`
|

|link:http://php.net/string[`string`^]
a|`$lang`
|
|===


[source%nowrap, php, subs=+macros]
[#getsuffix]
----

public getSuffix($itemId, $variationId, $withVariationId = true):link:http://php.net/string[string^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be removed in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_contracts_urlbuilderrepositorycontract_getsuffix[`UrlBuilderRepositoryContract::getSuffix()`]
====






.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$itemId`
|

|link:http://php.net/int[`int`^]
a|`$variationId`
|

|link:http://php.net/bool[`bool`^]
a|`$withVariationId`
|
|===


