:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:

[[io__modelwrapper]]
==== ModelWrapper





===== Namespace

`IO\Models`






===== Methods

[source%nowrap, php]
----

public static wrap($original, $args):void

----

    







.*Parameters*
|===
|Type |Name |Description
|
a|`$original`
|

|link:http://php.net/array[array^]
a|`$args`
|
|===


[source%nowrap, php]
----

public static wrapList($elements, $args):array

----

    







.*Parameters*
|===
|Type |Name |Description
|
a|`$elements`
|

|link:http://php.net/array[array^]
a|`$args`
|
|===


[source%nowrap, php]
----

public static wrapPaginated($paginated, $args):Plenty\Repositories\Models\PaginatedResult

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]




.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_models_paginatedresult[`PaginatedResult`]
a|`$paginated`
|

|link:http://php.net/array[array^]
a|`$args`
|
|===


[source%nowrap, php]
----

public __construct($attributes = []):void

----

    





Create a new Eloquent model instance.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|
|===


[source%nowrap, php]
----

public static clearBootedModels():void

----

    





Clear the list of booted models so they will be re-booted.

[source%nowrap, php]
----

public static withoutTouching($callback):void

----

    





Disables relationship model touching for the current class during given callback scope.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/callable[callable^]
a|`$callback`
|
|===


[source%nowrap, php]
----

public static withoutTouchingOn($models, $callback):void

----

    





Disables relationship model touching for the given model classes during given callback scope.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$models`
|

|link:http://php.net/callable[callable^]
a|`$callback`
|
|===


[source%nowrap, php]
----

public static isIgnoringTouch($class = null):bool

----

    





Determine if the given model is ignoring touches.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$class`
|
|===


[source%nowrap, php]
----

public fill($attributes):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Fill the model with an array of attributes.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|
|===


[source%nowrap, php]
----

public forceFill($attributes):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Fill the model with an array of attributes. Force mass assignment.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|
|===


[source%nowrap, php]
----

public qualifyColumn($column):string

----

    





Qualify the given column name by the model&#039;s table.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$column`
|
|===


[source%nowrap, php]
----

public newInstance($attributes = [], $exists = false):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Create a new instance of the given model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|

|link:http://php.net/bool[bool^]
a|`$exists`
|
|===


[source%nowrap, php]
----

public newFromBuilder($attributes = [], $connection = null):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Create a new model instance that is existing.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|

|link:http://php.net/string[string^]
a|`$connection`
|
|===


[source%nowrap, php]
----

public static on($connection = null):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Begin querying the model on a given connection.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$connection`
|
|===


[source%nowrap, php]
----

public static onWriteConnection():Illuminate\Database\Eloquent\Illuminate\Database\Query\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_query_builder[`Builder`]


Begin querying the model on the write connection.

[source%nowrap, php]
----

public static all($columns = []):void

----

    





Get all of the models from the database.

.*Parameters*
|===
|Type |Name |Description
|
a|`$columns`
|
|===


[source%nowrap, php]
----

public static with($relations):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Begin querying a model with eager loading.

.*Parameters*
|===
|Type |Name |Description
|
a|`$relations`
|
|===


[source%nowrap, php]
----

public load($relations):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Eager load relations on the model.

.*Parameters*
|===
|Type |Name |Description
|
a|`$relations`
|
|===


[source%nowrap, php]
----

public loadMissing($relations):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Eager load relations on the model if they are not already eager loaded.

.*Parameters*
|===
|Type |Name |Description
|
a|`$relations`
|
|===


[source%nowrap, php]
----

public loadCount($relations):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Eager load relation counts on the model.

.*Parameters*
|===
|Type |Name |Description
|
a|`$relations`
|
|===


[source%nowrap, php]
----

public update($attributes = [], $options = []):bool

----

    





Update the model in the database.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|

|link:http://php.net/array[array^]
a|`$options`
|
|===


[source%nowrap, php]
----

public push():bool

----

    





Save the model and all of its relationships.

[source%nowrap, php]
----

public save($options = []):bool

----

    





Save the model to the database.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|
|===


[source%nowrap, php]
----

public saveOrFail($options = []):bool

----

    





Save the model to the database using transaction.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$options`
|
|===


[source%nowrap, php]
----

public static destroy($ids):int

----

    





Destroy the models for the given IDs.

.*Parameters*
|===
|Type |Name |Description
|
a|`$ids`
|
|===


[source%nowrap, php]
----

public delete():bool

----

    





Delete the model from the database.

[source%nowrap, php]
----

public forceDelete():bool

----

    





Force a hard delete on a soft deleted model.

[source%nowrap, php]
----

public static query():Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Begin querying the model.

[source%nowrap, php]
----

public newQuery():Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Get a new query builder for the model&#039;s table.

[source%nowrap, php]
----

public newModelQuery():void

----

    





Get a new query builder that doesn&#039;t have any global scopes or eager loading.

[source%nowrap, php]
----

public newQueryWithoutRelationships():Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Get a new query builder with no relationships loaded.

[source%nowrap, php]
----

public registerGlobalScopes($builder):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Register the global scopes for this builder instance.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]
a|`$builder`
|
|===


[source%nowrap, php]
----

public newQueryWithoutScopes():void

----

    





Get a new query builder that doesn&#039;t have any global scopes.

[source%nowrap, php]
----

public newQueryWithoutScope($scope):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Get a new query instance without a given scope.

.*Parameters*
|===
|Type |Name |Description
|
a|`$scope`
|
|===


[source%nowrap, php]
----

public newQueryForRestoration($ids):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Builder

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_builder[`Builder`]


Get a new query to restore one or more models by their queueable IDs.

.*Parameters*
|===
|Type |Name |Description
|
a|`$ids`
|
|===


[source%nowrap, php]
----

public newEloquentBuilder($query):void

----

    





Create a new Eloquent query builder for the model.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_query_builder[`Builder`]
a|`$query`
|
|===


[source%nowrap, php]
----

public newCollection($models = []):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Collection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_collection[`Collection`]


Create a new Eloquent Collection instance.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$models`
|
|===


[source%nowrap, php]
----

public newPivot($parent, $attributes, $table, $exists, $using = null):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Relations\Pivot

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_relations_pivot[`Pivot`]


Create a new pivot model instance.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_model[`Model`]
a|`$parent`
|

|link:http://php.net/array[array^]
a|`$attributes`
|

|link:http://php.net/string[string^]
a|`$table`
|

|link:http://php.net/bool[bool^]
a|`$exists`
|

|link:http://php.net/string[string^]
a|`$using`
|
|===


[source%nowrap, php]
----

public toArray():array

----

    





Convert the model instance to an array.

[source%nowrap, php]
----

public toJson($options):string

----

    





Convert the model instance to JSON.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$options`
|
|===


[source%nowrap, php]
----

public jsonSerialize():array

----

    





Convert the object into something JSON serializable.

[source%nowrap, php]
----

public fresh($with = []):Illuminate\Database\Eloquent\static

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_static[`static`]


Reload a fresh model instance from the database.

.*Parameters*
|===
|Type |Name |Description
|
a|`$with`
|
|===


[source%nowrap, php]
----

public refresh():Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Reload the current model instance with fresh attributes from the database.

[source%nowrap, php]
----

public replicate($except = []):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Clone the model into a new, non-existing instance.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$except`
|
|===


[source%nowrap, php]
----

public is($model):bool

----

    





Determine if two models have the same ID and belong to the same table.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_model[`Model`]
a|`$model`
|
|===


[source%nowrap, php]
----

public isNot($model):bool

----

    





Determine if two models are not the same.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_eloquent_model[`Model`]
a|`$model`
|
|===


[source%nowrap, php]
----

public getConnection():Illuminate\Database\Eloquent\Illuminate\Database\Connection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_connection[`Connection`]


Get the database connection for the model.

[source%nowrap, php]
----

public getConnectionName():string

----

    





Get the current connection name for the model.

[source%nowrap, php]
----

public setConnection($name):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the connection associated with the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$name`
|
|===


[source%nowrap, php]
----

public static resolveConnection($connection = null):Illuminate\Database\Eloquent\Illuminate\Database\Connection

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_connection[`Connection`]


Resolve a connection instance.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$connection`
|
|===


[source%nowrap, php]
----

public static getConnectionResolver():Illuminate\Database\Eloquent\Illuminate\Database\ConnectionResolverInterface

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_connectionresolverinterface[`ConnectionResolverInterface`]


Get the connection resolver instance.

[source%nowrap, php]
----

public static setConnectionResolver($resolver):void

----

    





Set the connection resolver instance.

.*Parameters*
|===
|Type |Name |Description
|        xref:Miscellaneous.adoc#miscellaneous_database_connectionresolverinterface[`ConnectionResolverInterface`]
a|`$resolver`
|
|===


[source%nowrap, php]
----

public static unsetConnectionResolver():void

----

    





Unset the connection resolver for models.

[source%nowrap, php]
----

public getTable():string

----

    





Get the table associated with the model.

[source%nowrap, php]
----

public setTable($table):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the table associated with the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$table`
|
|===


[source%nowrap, php]
----

public getKeyName():string

----

    





Get the primary key for the model.

[source%nowrap, php]
----

public setKeyName($key):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the primary key for the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public getQualifiedKeyName():string

----

    





Get the table qualified key name.

[source%nowrap, php]
----

public getKeyType():string

----

    





Get the auto-incrementing key type.

[source%nowrap, php]
----

public setKeyType($type):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the data type for the primary key.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$type`
|
|===


[source%nowrap, php]
----

public getIncrementing():bool

----

    





Get the value indicating whether the IDs are incrementing.

[source%nowrap, php]
----

public setIncrementing($value):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set whether IDs are incrementing.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[bool^]
a|`$value`
|
|===


[source%nowrap, php]
----

public getKey():void

----

    





Get the value of the model&#039;s primary key.

[source%nowrap, php]
----

public getQueueableId():void

----

    





Get the queueable identity for the entity.

[source%nowrap, php]
----

public getQueueableRelations():array

----

    





Get the queueable relationships for the entity.

[source%nowrap, php]
----

public getQueueableConnection():string

----

    





Get the queueable connection for the entity.

[source%nowrap, php]
----

public getRouteKey():void

----

    





Get the value of the model&#039;s route key.

[source%nowrap, php]
----

public getRouteKeyName():string

----

    





Get the route key for the model.

[source%nowrap, php]
----

public resolveRouteBinding($value):Illuminate\Database\Eloquent\Illuminate\Database\Eloquent\Model

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_eloquent_model[`Model`]


Retrieve the model for a bound value.

.*Parameters*
|===
|Type |Name |Description
|
a|`$value`
|
|===


[source%nowrap, php]
----

public getForeignKey():string

----

    





Get the default foreign key name for the model.

[source%nowrap, php]
----

public getPerPage():int

----

    





Get the number of models to return per page.

[source%nowrap, php]
----

public setPerPage($perPage):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the number of models to return per page.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[int^]
a|`$perPage`
|
|===


[source%nowrap, php]
----

public __get($key):void

----

    





Dynamically retrieve attributes on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public __set($key, $value):void

----

    





Dynamically set attributes on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$value`
|
|===


[source%nowrap, php]
----

public offsetExists($offset):bool

----

    





Determine if the given attribute exists.

.*Parameters*
|===
|Type |Name |Description
|
a|`$offset`
|
|===


[source%nowrap, php]
----

public offsetGet($offset):void

----

    





Get the value for a given offset.

.*Parameters*
|===
|Type |Name |Description
|
a|`$offset`
|
|===


[source%nowrap, php]
----

public offsetSet($offset, $value):void

----

    





Set the value for a given offset.

.*Parameters*
|===
|Type |Name |Description
|
a|`$offset`
|

|
a|`$value`
|
|===


[source%nowrap, php]
----

public offsetUnset($offset):void

----

    





Unset the value for a given offset.

.*Parameters*
|===
|Type |Name |Description
|
a|`$offset`
|
|===


[source%nowrap, php]
----

public __isset($key):bool

----

    





Determine if an attribute or relation exists on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public __unset($key):void

----

    





Unset an attribute on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public __call($method, $parameters):void

----

    





Handle dynamic method calls into the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$method`
|

|link:http://php.net/array[array^]
a|`$parameters`
|
|===


[source%nowrap, php]
----

public static __callStatic($method, $parameters):void

----

    





Handle dynamic static method calls into the method.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$method`
|

|link:http://php.net/array[array^]
a|`$parameters`
|
|===


[source%nowrap, php]
----

public __toString():string

----

    





Convert the model to its string representation.

[source%nowrap, php]
----

public __wakeup():void

----

    





When a model is being unserialized, check if it needs to be booted.

[source%nowrap, php]
----

public attributesToArray():array

----

    





Convert the model&#039;s attributes to an array.

[source%nowrap, php]
----

public relationsToArray():array

----

    





Get the model&#039;s relationships in array form.

[source%nowrap, php]
----

public getAttribute($key):void

----

    





Get an attribute from the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public getAttributeValue($key):void

----

    





Get a plain attribute (not a relationship).

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public getRelationValue($key):void

----

    





Get a relationship.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public hasGetMutator($key):bool

----

    





Determine if a get mutator exists for an attribute.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public setAttribute($key, $value):void

----

    





Set a given attribute on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$value`
|
|===


[source%nowrap, php]
----

public hasSetMutator($key):bool

----

    





Determine if a set mutator exists for an attribute.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|
|===


[source%nowrap, php]
----

public fillJsonAttribute($key, $value):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set a given JSON attribute on the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$value`
|
|===


[source%nowrap, php]
----

public fromJson($value, $asObject = false):void

----

    





Decode the given JSON back into an array or object.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$value`
|

|link:http://php.net/bool[bool^]
a|`$asObject`
|
|===


[source%nowrap, php]
----

public fromFloat($value):void

----

    





Decode the given float.

.*Parameters*
|===
|Type |Name |Description
|
a|`$value`
|
|===


[source%nowrap, php]
----

public fromDateTime($value):string

----

    





Convert a DateTime to a storable string.

.*Parameters*
|===
|Type |Name |Description
|
a|`$value`
|
|===


[source%nowrap, php]
----

public getDates():array

----

    





Get the attributes that should be converted to dates.

[source%nowrap, php]
----

public getDateFormat():string

----

    





Get the format for database stored dates.

[source%nowrap, php]
----

public setDateFormat($format):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the date format used by the model.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$format`
|
|===


[source%nowrap, php]
----

public hasCast($key, $types = null):bool

----

    





Determine whether an attribute should be cast to a native type.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$types`
|
|===


[source%nowrap, php]
----

public getCasts():array

----

    





Get the casts array.

[source%nowrap, php]
----

public getAttributes():array

----

    





Get all of the current attributes on the model.

[source%nowrap, php]
----

public setRawAttributes($attributes, $sync = false):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the array of model attributes. No checking is done.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$attributes`
|

|link:http://php.net/bool[bool^]
a|`$sync`
|
|===


[source%nowrap, php]
----

public getOriginal($key = null, $default = null):void

----

    





Get the model&#039;s original attribute values.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$default`
|
|===


[source%nowrap, php]
----

public only($attributes):array

----

    





Get a subset of the model&#039;s attributes.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public syncOriginal():Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Sync the original attributes with the current.

[source%nowrap, php]
----

public syncOriginalAttribute($attribute):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Sync a single original attribute with its current value.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$attribute`
|
|===


[source%nowrap, php]
----

public syncOriginalAttributes($attributes):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Sync multiple original attribute with their current values.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public syncChanges():Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Sync the changed attributes.

[source%nowrap, php]
----

public isDirty($attributes = null):bool

----

    





Determine if the model or any of the given attribute(s) have been modified.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public isClean($attributes = null):bool

----

    





Determine if the model and all the given attribute(s) have remained the same.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public wasChanged($attributes = null):bool

----

    





Determine if the model or any of the given attribute(s) have been modified.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public getDirty():array

----

    





Get the attributes that have been changed since last sync.

[source%nowrap, php]
----

public getChanges():array

----

    





Get the attributes that were changed.

[source%nowrap, php]
----

public originalIsEquivalent($key, $current):bool

----

    





Determine if the new and old values for a given key are equivalent.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$key`
|

|
a|`$current`
|
|===


[source%nowrap, php]
----

public append($attributes):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Append attributes to query when building a query.

.*Parameters*
|===
|Type |Name |Description
|
a|`$attributes`
|
|===


[source%nowrap, php]
----

public setAppends($appends):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the accessors to append to model arrays.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$appends`
|
|===


[source%nowrap, php]
----

public getMutatedAttributes():array

----

    





Get the mutated attributes for a given instance.

[source%nowrap, php]
----

public static cacheMutatedAttributes($class):void

----

    





Extract and cache all the mutated attributes of a class.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[string^]
a|`$class`
|
|===


[source%nowrap, php]
----

public static observe($classes):void

----

    





Register observers with the model.

.*Parameters*
|===
|Type |Name |Description
|
a|`$classes`
|
|===


[source%nowrap, php]
----

public getObservableEvents():array

----

    





Get the observable event names.

[source%nowrap, php]
----

public setObservableEvents($observables):Illuminate\Database\Eloquent

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_database_eloquent[`Eloquent`]


Set the observable event names.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[array^]
a|`$observables`
|
|===


[source%nowrap, php]
----

public addObservableEvents($observables):void

----

    





Add an observable event name.

.*Parameters*
|===
|Type |Name |Description
|
a|`$observables`
|
|===


[source%nowrap, php]
----

public removeObservableEvents($observables):void

----

    





Remove an observable event name.

.*Parameters*
|===
|Type |Name |Description
|
a|`$observables`
|
|===


[source%nowrap, php]
----

public static retrieved($callback):void

----

    





Register a retrieved model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static saving($callback):void

----

    





Register a saving model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static saved($callback):void

----

    





Register a saved model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static updating($callback):void

----

    





Register an updating model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static updated($callback):void

----

    





Register an updated model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static creating($callback):void

----

    





Register a creating model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static created($callback):void

----

    





Register a created model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static replicating($callback):void

----

    





Register a replicating model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static deleting($callback):void

----

    





Register a deleting model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static deleted($callback):void

----

    





Register a deleted model event with the dispatcher.

.*Parameters*
|===
|Type |Name |Description
|
a|`$callback`
|
|===


[source%nowrap, php]
----

public static flushEventListeners():void

----

    





Remove all of the event listeners for the model.

[source%nowrap, php]
----

public static getEventDispatcher():Illuminate\Database\Eloquent\Illuminate\Contracts\Events\Dispatcher

----

    


====== *Return type:*        xref:Miscellaneous.adoc#miscellaneous_events_dispatcher[`Dispatcher`]


Get the event dispatcher instance.

