:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[io__itemsearchservice]]
= ItemSearchService

Execute elastic search requests.

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_services_itemsearchservice[`ItemSearchService`]
====


===== Namespace

`IO\Services\ItemSearch\Services`





.Properties
|===
|Type |Name |Description

|link:http://php.net/string[`string`^]
a|`$pluginNamespace`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#getresults]
----

public getResults($searches):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_services_itemsearchservice_getresults[`ItemSearchService::getResults()`]
====




Get search results for multiple search requests.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$searches`
|Map of search factories to execute.
|===


[source%nowrap, php, subs=+macros]
[#getresult]
----

public getResult($searchFactory):link:http://php.net/array[array^]

----

[WARNING]
.Deprecated! 
====

since 5.0.0 will be deleted in 6.0.0

see:xref:stable7@interface::Webshop.adoc#webshop_services_itemsearchservice_getresult[`ItemSearchService::getResult()`]
====




Get result of a single search factory;

.*Parameters*
|===
|Type |Name |Description
|xref:IO/Services/ItemSearch/Factories/BaseSearchFactory.adoc#[`BaseSearchFactory`]
a|`$searchFactory`
|The factory to get results for.
|===


